slug: amazon-cloudwatch-internet-monitor
description: |-
  ## What is Amazon CloudWatch Internet Monitor?

  Amazon CloudWatch Internet Monitor provides visibility into how internet issues impact the performance and availability between your applications hosted on AWS and your end users.

  ### Get started!

  Start monitoring Amazon CloudWatch Internet Monitor by sending your Amazon CloudWatch Internet Monitor Logs to New Relic. 

  Check out our Amazon CloudWatch Internet Monitor documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's Log monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/logs/forward-logs/cloudfront-web-logs/) to learn more about New Relic monitoring for Amazon CloudFront. 
summary: Monitor Amazon CloudWatch Internet Monitor in New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
  - Aarushi Jain
title: Amazon CloudWatch Internet Monitor
documentation:
  - name: Amazon CloudWatch Internet Monitor installation docs
    description: Monitor Amazon CloudWatch Internet Monitor in New Relic.
    url: https://docs.newrelic.com/docs/logs/forward-logs/cloudfront-web-logs/
keywords:
  - aws
  - amazon web services
  - cloudwatch
  - monitor
  - internet
dashboards:
  - amazon-cloudwatch-internet-monitor
dataSourceIds:
  - amazon-cloudwatch-metric-streams
alertPolicies:
  - amazon-cloudwatch-internet-monitor
