id: ray
displayName: Ray
description: Identify and optimize Ray performance with New Relic Ray monitoring.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ray-integration/
icon: logo.svg
keywords:
  - ray
  - python
  - python3
  - mlops
  - ai
  - generative ai
  - machine learning
  - artificial intelligence
