# quickstarts/example-category/example-quickstart/config.yml

# This is automatically created by the system, this field should not be included by the author when creating a new quickstart.
id: 00000-0000-0000-0000000

# Name of the quickstart (required)
slug: nvidia-gpu monitoring

# Used as the display name for the quickstart
title: Nvidia GPU Monitoring

description: |
  ## Have a quick-start that can guide through installation and curated experiences for nvidiaGPU monitoring
  * Data Sources 
  * Dashboard
  * Alerts

summary: |
  Install plan based on infra-agent and documentation to explain the required steps

# Possible values: New Relic | Verified | Community
# Please consult with pull request reviewers if you think your quickstart should have a support level other than "Community"
level: NewRelic

authors:
  - New Relic

# These keywords can be mapped to category terms
# which help to categorize quickstarts.
# To have your quickstart appear under a certain category,
# these keywords must include a matching category term,
# see link in the keywords row of the table below.
keywords:
  - nvidia
  - gpu
  -infrastructure
  

# Relevant documentation for this quickstart
documentation:
  - name: Installation docs
    url: docs.newrelic.com
    description: Short description of the documentation link

# An icon or logo for the quickstart
icon: nvidia-logo.png

# References to dashboards by file path, the first entry references a dashboard located at `dashboards/example-dashboard`
# For more information on dashboard definitions, see the section below.
dashboards:
  - Nvidia GPU Monitoring

# References to alert policies by file path, the first entry references an alert policy located at `alerts-policies/example-alert-policy`
# For more information on alert policy definitions, see the section below.
alertPolicies:
  - high-gpu-memory-utilization


# References to data sources by their id. These can be either CORE or a COMMUNITY data source.
# For more information on data source definitions, see the section below.
dataSourceIds:
  - example-data-source