id: nvidia-triton
displayName: NVIDIA Triton
description: |
  Monitor and analyze your NVIDIA Triton inference server with New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-triton-integration/
icon: logo.png

