id: 
slug: newrelic-java-vertx-extensions
title: New Relic Java Instrumentation for Vert.x Extensions
description: |
  # What is Vert.x?
  Vert.x, a reactive, event-driven framework for the JVM, empowers building high-performance, 
  scalable apps with minimal resources. Its toolkit supports diverse use cases including web apps, 
  microservices, and IoT solutions.
summary: |
  Offers comprehensive instrumentation for monitoring key components od Vert.x such as Cassandra, JDBCClient, 
  Coroutines, Kafka, RxJava, SQL Clients, Redis, MongoDB, Reactive, and Service Proxy.

level: Community

keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - sql
  - kafka
  - mssql
  - postgres
  - oracle
  - db2
  - cassandra
  - jdbc
  - redis
  - rabbitmq
  - rxjava
  - mongodb
  - reactive
  - coroutines

icon: vertx-ext.svg
authors:
  - New Relic Labs
dataSourceIds:
  - newrelic-java-vertx-extensions
documentation:
  - name: New Relic Java Instrumentation for Vert.x Extensions
    description: |
      Provides instrumentation for monitoring the Vert.x Cassandra, JDBCClient, Coroutines, Kafka, 
      RxJava, SQL Clients, Redis, MongoDB, Reactive and Service Proxy.
    url: https://github.com/newrelic/newrelic-java-vertx-extensions/tree/main#installation

dashboards:
  - java
alertPolicies:
  - java
