id: ocsf
displayName: ocsf
description: |
  Monitor and instrument your OCSF with New Relic to gain deep insights into your performance.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ocsf-integration/
icon: logo.png