id: nvidia-dcgm
displayName: NVIDIA DCGM
description: |
  Monitor and analyze your NVIDIA DCGM infrastructure with New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-dcgm-integration/
icon: logo.png
keywords:
  - NVIDIA DCGM
  - dcgm
  - gpu