slug: azure-recovery-services-vaults
title: Azure Recovery Services Vaults Through Azure Monitor Integration
description: |-
  ## What is Azure Recovery Services Vaults?

  Azure Recovery Services Vaults is a cloud-based backup and disaster recovery solution that provides centralized management for various data sources. It offers features like backup and restore, disaster recovery, data archiving, security, and compliance to ensure business continuity and protect data from accidental deletion or loss.

  ### New Relic Azure Recovery Services Vaults quickstart features

  A standard dashboard that tracks key indicators like Backup, Restore, Data Source and more. It runs custom queries and visualizes the data immediately.

  ### Why monitor Azure Recovery Services Vaults with New Relic?

  [New Relic Azure Recovery Services Vaults](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-recovery-services-vaults-monitor-integration/) monitoring quickstart empowers you to track the performance of Azure Recovery Services Vaults via different metrics including Backup, Restore, Datasource and more.

  Our integration features a standard dashboard that provides interactive visualizations to explore your data, understand context, and get valuable insights.

  Start ingesting your Azure data today and get immediate access to our visualization dashboards so you can optimize your Azure service.
summary: |-
  Monitor Azure Recovery Services Vaults Through Azure Monitor Integration by connecting Azure to New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
  - New Relic Partner
documentation:
  - name: Azure Recovery Services Vaults installation docs
    description: |
      Monitor Azure Recovery Services Vaults by connecting Azure to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-recovery-services-vaults-monitor-integration/
keywords:
  - azure
  - azure recovery
  - azure recovery services vaults
  - azure service vaults
  - azure vault
dashboards:
  - azure-recovery-services-vaults
dataSourceIds:
  - azure-monitor
alertPolicies:
  - azure-recovery-services-vaults