id: gridgain-data-source
displayName: GridGain
description: |
  Collect the metrics and logs from your GridGain or Apache Ignite cluster using New Relic.
icon: GridGain-Logo.jpg
install:
  primary:
    link:
      url: https://www.gridgain.com
keywords:
  - database
  - java
  - cluster
  - sql
  - cache
  - compute-grid
  - apache-ignite
  - ignite
categoryTerms:
  - metrics
  - logs
