id: gridgain-data-source
displayName: GridGain
description: |
  Collect the metrics and logs from your GridGain or Apache Ignite cluster using New Relic.
icon: gridgain.svg
install:
  primary:
    link:
      url: https://github.com/sdarlington/gridgain-observation/tree/main/newrelic
keywords:
  - database
  - java
  - cluster
  - sql
  - cache
  - compute-grid
  - apache-ignite
  - ignite
categoryTerms:
  - metrics
  - logs
