slug: docarray-hnswsearch
description: |
  ## Why should you monitor your usage of DocArray HnswSearch?
  Monitor your vector searches on DocArray HnswSearch to get visibility on what you send to DocArray HnswSearch, responses retrieved from DocArray HnswSearch, latency, usage and errors.

  ### Track the query performance of your Vector DB
  Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.

  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.

  ## Comprehensive monitoring quickstart for your DocArray HnswSearch app
  Our DocArray HnswSearch quickstart provides metrics including Identify popular queries, sources, and content.

  ## What’s included in this quickstart?
  New Relic DocArray HnswSearch monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your DocArray HnswSearch app. These reports include:
  - Vector searches
  - Alerts for errors, search per vector store, and response time
  - Identify popular queries, sources, and content
summary: |
  Monitor your Vector search's performance and quality with New Relic DocArray HnswSearch quickstart
icon: logo.svg
level:
  - New Relic
authors:
  - New Relic
  - Ramana Reddy
title: DocArray HnswSearch
documentation:
  - name: DocArray HnswSearch integration documentation
    description: |
      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - DocArray
  - HnswSearch
  - text search
  - image search
  - video search
  - AI
  - machine learning
  - open source
  - Hnsw Search
  - Doc Array
  - vector search
  - mlops
  - NR1_addData
alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb
