slug: amazon-mediatailor
description: |-
  ## What is Amazon MediaTailor?
  AWS Elemental MediaTailor is a channel assembly and personalized ad-insertion service for video providers to create linear over-the-top (OTT) channels using existing video content. The service then lets you monetize those channels or other live streams with personalized advertising.
  ### Get started!
  Start monitoring Amazon MediaTailor by connecting Amazon Web Services (AWS) to New Relic! Take a look at our documentation for information on how to set up this integration.
  ### More info
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-mediatailor-monitoring-integration/) to learn more about New Relic monitoring for Amazon MediaTailor.
summary: |-
  Monitor Amazon MediaTailor by connecting AWS to New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Amazon MediaTailor
documentation:
  - name: Amazon MediaTailor installation docs
    description: |
      Monitor Amazon MediaTailor by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-mediatailor-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - MediaTailor
  - amazon media tailor
  - media tailor
  - amazon mediatailor
alertPolicies:
  - amazon-mediatailor
dashboards:
  - amazon-mediatailor
dataSourceIds:
  - amazon-cloudwatch-metric-streams