slug: vectara
description: |
  ## Why should you monitor your usage of Vectara?
  Monitor your vector searches on Vectara to get visibility on what you send to Vectara, responses retrieved from Vectara, latency, usage and errors. 
  ### Track the query performance of your Vector DB
  Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.
  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.

  ### What’s included in this quickstart?
  New Relic Vectara monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your Vectara app. These reports include:
  - Vector searches
  - Alerts for errors, search per vector store, and response time
  - Identify popular queries, sources, and content

summary: |
  Monitor your Vector search's performance and quality with New Relic Vectara quickstart.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Vectara
documentation:
  - name: Vectara integration documentation
    description: |
      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - vectara
  - vector store
  - machine learning
  - vector search
  - artificial intelligence
  - AI
  - ML
  - NLP
  - data science
  - mlops
  - NR1_addData
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb