slug: mongodb-atlas-vector-search
description: |
  ## Why should you monitor your usage of MongoDB Atlas Vector Search?
  Monitor your vector searches on MongoDB Atlas Vector Search to get visibility on what you send to MongoDB Atlas Vector Search, responses retrieved from MongoDB Atlas Vector Search, latency, usage and errors.

  ### Track the query performance of your Vector DB
  Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.

  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.

  ## Comprehensive monitoring quickstart for your MongoDB Atlas Vector Search app
  Our MongoDB Atlas Vector Search quickstart provides metrics including Identify popular queries, sources, and content.

  ## What’s included in this quickstart?
  New Relic MongoDB Atlas Vector Search monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your MongoDB Atlas Vector Search app. These reports include:
  - Vector searches
  - Alerts for errors, search per vector store, and response time
  - Identify popular queries, sources, and content
summary: |
  Monitor your Vector search's performance and quality with New Relic MongoDB Atlas Vector Search quickstart
icon: logo.svg
level:
  - New Relic
authors:
  - New Relic
  - Ramana Reddy
title: MongoDB Atlas Vector Search
documentation:
  - name: MongoDB Atlas Vector Search integration documentation
    description: |
      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - mongodb
  - atlas vector search
  - mongodb atlas vector search
  - vector search
  - vector database
  - cloud-based vector search
  - managed vector search
  - machine learning
  - artificial intelligence
  - AI
  - ML
  - NLP
  - CV
  - text search
  - image search
  - video search
  - product search
alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb
