slug: docker-otel
title: Docker (OpenTelemetry)
summary: |
  Monitoring Docker is critical to get instant performance metrics for containerized applications across your entire environment. Install New Relic Docker monitoring quickstart to proactively instrument Docker with OpenTelemetry Dockerstats receiver.
description: |
  ## How to monitor Docker with New Relic?

  Dockerstats OpenTelemetry receiver collects metrics from your running Docker containers on the host where OpenTelemetry Collector is installed.
  The collected metrics allow you to observe the usage of CPU, memory, network, and more.

  A New Relic container Entity will represent each of the containers making it easy to explore, alert, and compare metrics related to them.

  Our monitoring quickstart also contains a Dashboard with the aggregated metrics from all the containers that are reporting to your account with the possibility to apply filters to target the desired workload.

  ### Why monitor Docker with New Relic?

  New Relic's Docker monitoring quickstart empowers you to get a 360° visibility for your apps, server infrastructure, and Dockerized containers—all in one place. Since your team is likely charged with delivering high-quality software that yields a great customer experience, monitoring Docker is essential. It allows you to keep up that customer experience with your users remaining unaffected by any changes to platforms, tools, languages, or frameworks. 

icon: logo.svg
level: New Relic
authors:
  - New Relic
installPlans:
  - docker-otel
dataSourceIds:
  - docker-otel
documentation:
  - name: Docker (OpenTelemetry) installation docs
    description: |
      Docker is a set of platform as a service products that use OS-level
      virtualization to deliver software in packages called containers.
    # TODO link to the doc page when available.
    url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-configs/

keywords:
  - containers
