id: stripe
displayName: Stripe
description: |
  Unleash the full potential of Stripe monitoring through the seamless integration of our New Relic agents.
install:
  primary:
    link:
      url: https://docs.newrelic.com/
icon: logo.png
keywords: 
   - stripe
   - node.js