id: elixir
displayName: Elixir agent installation
description: Start monitoring the performance of an Elixir application or service by installing the New Relic Elixir agent.
install:
  primary:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: elixir
    requires_account: false
icon: logo.png
