slug: hcp-consul-otel
title: HCP Consul (OTeL collector)
description: |-
  ## HCP Consul
  HCP (Hashicorp Cloud Platform) Consul is a version of Consul in which the control plane is managed by HashiCorp Cloud Platform. 

  HCP Consul is a service mesh and service discovery solution provided by Hashicorp. It enables platform operators to quickly deploy a fully managed, secure-by-default service mesh, helping developers discover and securely connect any application on any runtime, including Kubernetes, Nomad, and Amazon ECS.

  ### Monitor HCP Consul metrics with New Relic
  Keeping your Consul and Nomad clusters healthy can help with optimizing SQL query times, troubleshooting slow HTTP response times, and real-time alerting on down-time for your Hashicorp clusters. Monitoring your Hashicorp cluster metrics is pivotal for keeping your Hashicorp mesh services operating at full capacity.

  New Relic supports monitoring of HCP Consul and Envoy metrics through the OpenTelemetry (OTeL) integration. OTeL aggregates all the metrics exposed by HCP Consul and pushes them to New Relic for data visualization and alerting.

  ### HCP Consul quickstart highlights
  The HCP Consul quickstart for New Relic provides a pre-made dashboard with HCP Consul Server metrics. 
  
  For Envoy metrics, you can run the telemetry collector based on [HCP guidance](https://developer.hashicorp.com/hcp/docs/consul/monitor/consul-central/observability/telemetry-collector#forward-metrics-to-another-collector), and forward them to the same collector.


summary: Monitor your HCP Consul environment with the an OTeL collector
level: Verified
authors:
  - New Relic
  - Joseph Counts
keywords:
  - hcp
  - hcp-consul
  - hashicorp
  - open-telemetry
  - consul
  - newrelic partner
  - infrastructure
documentation:
  - name: Configuration documentation
    url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hcp-consul/
    description: HCP Consul configuration documentation
icon: logo.svg
dataSourceIds:
  - hcp-consul-otel
dashboards:
  - hcp-otel-consul
