slug: stripe
description: |
  ## Comprehensive monitoring quickstart for Stripe
  Stripe serves as an online payment processing and credit card platform designed for businesses. By monitoring your Stripe applications, you ensure peak performance, maximize system availability, and uphold the overall health of your system.
  ## Why monitor your Stripe app?
   By leveraging Stripe monitoring by New Relic, you gain invaluable visibility into the overall health and performance of your distributed system. This empowers you to swiftly identify and address any potential issues, ensuring optimal operational efficiency.
  ## What’s included in this quickstart?
  New Relic Stripe monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboard (successful and canceled transaction, net revenue ($), transaction volume, application throughput and many more)
  - Alerts (downtime, transaction succes rate and cpu usage)
summary: |
   Unleash the full potential of Stripe monitoring through the seamless integration of our New Relic agents.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Stripe
documentation:
  - name: Stripe integration documentation
    description: |
      Unleash the full potential of Stripe monitoring through the seamless integration of our Node.js agent.
    url: https://docs.newrelic.com/
keywords:
  - stripe
  - node.js
dataSourceIds:
  - stripe
dashboards:
  - stripe
alertPolicies:
  - stripe