slug: chromadb
description: |
  ## Why should you monitor ChromaDB?
  Monitoring your ChromaDB AI is essential for several reasons:
  ### Performance optimization:
  Monitoring allows you to identify and address performance bottlenecks, slow queries, and other issues that can impact the speed and efficiency of your chroma keying processes.
  ### Fault detection: 
  Monitoring allows you to quickly detect and respond to database failures or errors.
  ### Data integrity:
  Monitoring helps you identify and resolve data consistency issues or data corruption incidents that could affect the quality of your chroma keying results.

  ## Comprehensive monitoring quickstart for ChromaDB
  Monitoring ChromaDB is essential for maintaining the reliability, performance, and security of your database system, which, in turn, supports your chroma keying processes without interruptions.

  ## What’s included in the ChromaDB quickstart?
  New Relic ChromaDB monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your ChromaDB. These reports include:
  - Dashboards (average tokens, LLM completion’s details, chain’s details, tool details, top tool names and many more)
  - Alerts (errors, request per model and response time)
summary: |
  Improve your ChromaDB performance with New Relic ChromaDB quickstart.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: ChromaDB
documentation:
  - name: ChromaDB integration documentation
    description: |
      Implement monitoring and instrumentation for your ChromaDB, and ensure that your ChromaDB's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - chromadb
  - chromadb ai
  - chroma db
  - mlops
  - large language model
  - natural language processing
  - machine learning
  - artificial intelligence
  - ai
  - generative ai
  - NR1_addData

alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb
