id: a92448c6-19ab-4c6e-946d-22e4171e594f
slug: aws-rekognition
description: |-
  ## Monitor your AWS Rekognition and AWS Rekognition Operation Metrics

  With New Relic's Amazon Rekognition integration, you now can see all your Rekognition data on New Relic Instant Observability Platform.

  ### Get started!

   Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-rekognition-monitoring-integration/) to learn more about New
   Relic monitoring and integration with Amazon Rekognition.

summary: Use New Relic - Amazon Rekognition Integration to analyse your rekognition data with New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Amazon Rekognition
documentation:
  - name: Amazon Rekognition installation docs
    description: |
      Monitor AWS Rekognition by connecting AWS to New Relic.
    url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-rekognition-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - rekognition
dataSourceIds:
  - aws-rekognition
dashboards:
  - aws-rekognition
