slug: supabase
description: |
  ## Why should you monitor Supabase?
  By monitoring Supabase, you can maintain the stability, security, and performance of your applications

  ## Comprehensive monitoring quickstart for Supabase
  Our Supabase quickstart offers key metrics, such as database performance, storage metrics, and error rate, which are valuable resources to help you optimize the performance of Supabase.

  ## What’s included in the Supabase quickstart?
  New Relic Supabase monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (response time, searches by provider, document retrieved and etc)
  - Alerts (zero documents retrieved and api response time)
summary: |
  New Relic can be used to monitor the performance of applications and services that interact with Supabase.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Qdrant
documentation:
  - name: Supabase integration documentation
    description: |
      Implement monitoring and instrumentation for your Supabase, and ensure that your Supabase data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - Supabase
  - Real-time Database
  - mlops
  - machine learning
  - artificial intelligence
  - ai
  - NR1_addData

alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb