id: 2567c5e0-06de-4ff6-a4f2-6cbe5aed07b3

# Name of the quickstart
name: nginx

# Title of the quickstart
title: Nginx

# Description of the quickstart
description: |+
  Official New Relic quickstart for Nginx
  Use this quickstart together with the New Relic Nginx On Host Integration to get insight into the performance of your Nginx instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.jpeg
website: https://nginx.org/

# Authors of the quickstart
authors:
  - New Relic
  - Daniel Gola

documentation:
  - name: Nginx
    description: >-
      Web server which can also be used as a reverse proxy, load balancer, mail proxy, and HTTP cache.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration/

installPlans:
  - nginx-integration

keywords:
  - infrastructure
  - web
