# A unique identifier for the data source
id: opslevel

# Display name for the data source
displayName: OpsLevel

description: |
  Be prepared for incidents and solve performance issues faster by combining the complete context in OpsLevel with New Relic’s monitoring capabilities.

install:
  primary:
    link: https://docs.opslevel.com/docs/new-relic-integration

# An icon for display within the catalog
icon: logo.svg

# Searchable words or phrases
keywords:
  - newrelic partner
  - messaging
  - opslevel
