id: nvml
displayName: NVML
description: |
  Monitor and analyze your NVML infrastructure with New Relic.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: nvml
        frameworkConfigId: nvml
      requiresAccount: false
icon: logo.png
keywords:
  - NVIDIA
  - NMVL
  - GPU Management
  - AI Management
  - GPU Optimization
  - AI Optimization
