id: nvml
displayName: NVML
description: |
  Monitor and analyze your NVML infrastructure with New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvml-integration/
icon: logo.png
keywords:
  - NVIDIA
  - NMVL
  - GPU Management
  - AI Management
  - GPU Optimization
  - AI Optimization
