id: sendmail
displayName: Sendmail
description: |
  Use our infrastructure agent and NRI-Flex configuration to export Sendmail data to New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/sendmail-integration/
icon: logo.png
