id: linkerd
displayName: Linkerd
description: |
  Enhance the performance monitoring and instrumentation of your Linkerd by integrating New Relic.
install:
  primary:
     nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: linkerd
        frameworkConfigId: linkerd
      requiresAccount: false
keywords:
  - linkerd
icon: logo.png
