id: linkerd
displayName: Linkerd
description: |
  Enhance the performance monitoring and instrumentation of your Linkerd by integrating New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/linkerd-integration/
keywords:
  - linkerd
icon: logo.png
