id: apache-mesos
displayName: Apache Mesos
description: |
  Enhance the performance monitoring and instrumentation of your Apache Mesos by integrating New Relic.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: apache-mesos
        frameworkConfigId: apache-mesos
      requiresAccount: false
keywords:
  - apache mesos
  - mesos
 