id: docker-otel
displayName: Docker (OpenTelemetry)
description: |
  The Open Telemetry Dockerstats receiver allows you to collect metrics related to the usage of CPU, memory, network, and more.
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/other-examples/collector/docker


icon: logo.svg

keywords:
  - infrastructure
  - containers
  - open telemetry
  - docker
  - featured
categoryTerms:
  - containers
