id: docker-otel
displayName: Docker (OpenTelemetry)
description: |
  The Dockerstats receiver allows you to collect metrics related to the usage of CPU, memory, network, and more.
install:
  primary:
    link:
      # TODO link to the doc page when available.
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-configs/

icon: logo.svg

keywords:
  - infrastructure
  - containers
categoryTerms:
  - containers
