slug: keras
description: |
  ## Why monitor your Keras?
  Keras is an open-source library that provides a Python interface for artificial neural networks. Monitoring Keras is essential for maintaining the smooth operation of the system and ensuring the delivery of precise data insights.
  This necessity arises due to the following factors:
  ### Improve performance:
  Keras can be slow, especially for large models. By monitoring the Keras, you will be able to identify areas where performance can be improved.
  ### Model health: 
  Keep track of the model's health and reliability over time to maintain its accuracy and relevance.
  ### Data quality: 
  Monitor data preprocessing and input quality to maintain the integrity of model inputs.
  
  ## Comprehensive monitoring quickstart for Keras
  Monitoring your Keras AI is an important step in ensuring the quality, accuracy, performance, compliance, user experience, and decision-making. By tracking key metrics, you will identify and address errors, improve performance, and comply with regulations. 

  ## What’s included in the Keras quickstart?
  New Relic Keras monitoring quickstart provides quality out-of-the-box reporting:
  - Real-time visibility: Get insights into the performance of your Keras in real time
  - Security insights: Get insights into the security of your Keras and identify potential threats
  - Be proactively alerted about critical issues related to your Keras's status
  - Gain code-related insights about your Keras's health and status
summary: |
   Enhance the performance of your Keras by integrating with New Relic for overall Keras monitoring and optimization.
icon: logo.png
level: 
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Keras
documentation:
  - name: Keras integration documentation
    description: |
     Implement monitoring and instrumentation for your Keras, and ensure that your Keras's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  keras
  -  keras ai
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence