id: openstack-controller
displayName: Openstack Controller
description: |
  Use New Relic to monitor and analyze your Openstack Controller infrastructure.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/openstack-controller-integration/
icon: logo.png
keywords:
  - openstack controller
  - openstack
  - nova controller
  - neutron controller
  - cinder controller
  - Keystone controller