id: atlassian-jira
displayName: Atlassian JIRA
description: |
  Jira is a proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management. You can Integrate New Relic with Atlassian Jira(Cloud) and automatically create and update Jira issues.
icon: logo.png
install:  
  primary:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: atlassian-jira
    requires_account: false
keywords:
  - JIRA
  - Atlassian
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations
  - newrelic partner
categoryTerms:
  - newrelic partner
