id: e9b4adc3-a2e0-4177-b1f2-6b73254aa960

slug: onepane

title: OnePane

description: |
  
  ## OnePane

  OnePane acts as a central hub, bringing together information from various systems like Cloud, DevOps tools and Monitoring. 
  This unified view lets you see how changes and events from these systems correlate with incidents, significantly speeding up the process of identifying the root cause (RCA).

  ### Why OnePane?

  By correlating updates in code, configurations, and deployments from various systems with New Relic incidents and entities, you can efficiently and quickly identify the exact root cause of an error. This way, you can see precisely which change triggered the problem, saving you a considerable amount of time in troubleshooting.


  - Show changes and infrastructure events alongside errors to pinpoint potential root causes.
  - Enable root cause investigation by correlating incidents with change data and infrastructure data.

  ### Get started!

  - To get started with OnePane, you can sign up for a [free cloud account](https://console.onepane.ai/).
  - Integrate OnePane with New Relic to analyse deployment, change, and infrastructure event data to identify possible root causes. You can also review [additional documentation at OnePane](https://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment).

summary: By correlating deployment change and infrastructure change from OnePane with New Relic, you can enable faster root cause identification for the incidents.

level: Verified

authors:
  - OnePane

keywords:
  - devops
  - change tracking
  - incident correlation
  - root cause analysis
  - llm

documentation:
  - name: Installation docs
    url: https://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment
    description: In order accelerate root cause analysis, Onepane integrates with New Relic to correlate incidents with changes and infrastructure events.

icon: logo.png

dataSourceIds:
  - onepane