slug: nvidia-dcgm
description: |
  ## Why monitor NVIDIA DCGM?
  monitoring NVIDIA DCGM is essential for maintaining the health and efficiency of your GPU infrastructure in a data center. It helps with performance optimization, fault detection, resource management, energy efficiency, and overall data center health, while also aiding in troubleshooting, security, and compliance.
  
  ## Comprehensive monitoring quickstart for NVIDIA DCGM
  New Relic comprehensive monitoring of your GPU infrastructure in your data center. This setup will allow you to monitor GPU performance and health while leveraging the capabilities of New Relic for data visualization, alerting, and analysis.

  ## What’s included in this quickstart?
  New Relic NVIDIA DCGM monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (power usage, gpu utilisation, clocks, etc)
  - Alerts for ZooKeeper (gpu temperature, xid error)


summary: |
   Monitor and analyze your NVIDIA DCGM infrastructure with New Relic.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: NVIDIA DCGM
documentation:
  - name: NVIDIA DCGM integration documentation
    description: |
      Monitor and instrument your NVIDIA DCGM with New Relic to gain deep insights into your performance.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-dcgm-integration/
keywords:
  - NVIDIA DCGM
  - dcgm
  - gpu
dataSourceIds:
  - nvidia-dcgm
dashboards:
  - nvidia-dcgm
alertPolicies:
  - nvidia-dcgm