id: fivetran
displayName: Fivetran
description: |
  Fivetran is a SaaS solution that provides automated data movement.
icon: fivetran-logo.png
install:
  primary:
    link:
      url: https://www.fivetran.com/
keywords:
  - data pipeline
  - elt
  - fivetran
categoryTerms:
  - newrelic partner
  - logs
