id: 289983fe-378e-4690-9302-2490e2afe11c

# Name of the quickstart
name: redis

# Title of the quickstart
title: Redis

# Description of the quickstart
description: |+
  Official New Relic quickstart for Redis
  Use this quickstart together with the New Relic Redis On Host Integration to get insight into the performance of your Redis instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://redis.io/

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak

documentation:
  - name: Redis
    description: >-
      Open source, key-value data structure store for use as a database, cache, and message broker with wide protocol and dataset support.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/

installPlans:
  - redis-integration

keywords:
  - infrastructure
  - database
