slug: linkerd
description: |
  ## Why monitor your Linkerd?
  Monitoring Linkerd with New Relic provides a robust framework for ensuring the reliability, performance, and security of your microservices architecture.

  ## Comprehensive monitoring quickstart for Linkerd
  Integrating Linkerd with New Relic provides powerful observability and monitoring capabilities, ensuring your microservices run smoothly and efficiently. This enables you to monitor your service mesh more effectively, reducing troubleshooting time and allowing you to focus on developing new features and enhancing your applications.

  ## What’s included in the Linkerd quickstart?
  New Relic Linkerd monitoring quickstart ability to cover quality on out-of-the-box reporting:

  - Dashboards (request_total, response_total and tcp_open_total)
  - Alerts (high latency, high error rate, etc..)
  
summary: |
  Gain valuable insights into your Linkerd deployment with New Relic's monitoring and analysis capabilities.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Shivani Kashyap
title: Linkerd
documentation:
  - name: Linkerd integration documentation 
    description: |
      Enhance the performance monitoring and instrumentation of your Linkerd by integrating New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/linkerd-integration/
keywords:
  - linkerd
  - NR1_addData
  - NR1_sys
dashboards:
  - linkerd
alertPolicies:
  - linkerd
dataSourceIds:
  - linkerd