# A unique identifier for the data source
id: email-notifications

# Display name for the data source
displayName: Email Notifications

description: |
  Send your New Relic alert notifications via email. You can send email notifications to users with or without New Relic accounts.

install:
  primary:
    link: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#email

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - email
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations
