slug: anthropic
description: |
  ## Why should you monitor Anthropic?
  Monitoring Anthropic AI is essential to ensure that AI models operate effectively, efficiently, and securely while providing a high-quality user experience. 
  ### Performance optimization: 
  Continuous monitoring helps ensure that Anthropic AI models are performing optimally. 
  ### Early issue detection:
  Detect and address issues early to prevent them from affecting model performance. 

  ## Comprehensive monitoring quickstart for Anthropic
  Anthropic's quickstart tracks metrics, like accuracy and efficiency, to fine-tune models for better results and catch issues like overfitting or data shifts early.

  ## What’s included in the Anthropic quickstart?
  New Relic Anthropic monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your Anthropic. These reports include:
  - Dashboards (average tokens, LLM completion’s details, chain’s details, tool details, top tool names and many more)
  - Alerts (errors, request per model and response time)
summary: |
  Improve the performance of your Anthropic by integrating New Relic for comprehensive Anthropic monitoring and optimization.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Anthropic
documentation:
  - name: Anthropic integration documentation
    description: |
      Implement monitoring and instrumentation for your Anthropic, and ensure that your Anthropic's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain
keywords:
  - anthropic
  - anthropic ai
  - mlops
  - large language model
  - natural language processing
  - machine learning
  - artificial intelligence
  - ai
  - generative ai
alertPolicies:
  - langchain
dashboards:
  - langchain
