id: dbt-cloud 
displayName: dbt Cloud 
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. Our dashboard and alerts help you find issues with dbt Cloud runs and resources (models, seeds, snapshots, tests). Includes the ability to collect failed test rows from dbt tests in Snowflake.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/dbt-cloud/dbt-cloud-integration/
keywords:
  - dbt cloud
  - dbt

documentation:
  - name: Github Repository 
    description: |
      Github repository with the Airflow DAG and related documentation.
    url: >-
      https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration/