id: dbt-cloud 
displayName: dbt Cloud 
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. Our dashboard and alerts help you find issues with dbt Cloud runs and resources.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: dbt-cloud 
        frameworkConfigId: dbt-cloud 
      requiresAccount: false
keywords:
  - dbt cloud
  - dbt

documentation:
  - name: Github Repository 
    description: |
      Github repository with the Airflow DAG and related documentation.
    url: >-
      https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration/  

