id: browser-signals
displayName: Browser Signals
description: |
  Comprehensive Browser dashboard providing actionable insights, including CWV, Throughput, Errors & Latency. 
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide/
icon: logo.svg
