# A unique identifier for the data source
id: nvidia-gpu

# Display name for the data source
displayName: Nvidia GPU Monitoring

description: |
  Monitor Nvidia GPUs based on the Nvidia SMI utility.

install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-gpu-integration/

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - infrastructure
  - nvidia
  - gpu

# Terms related to the categories for the data source.
categoryTerms:
  - infrastructure