id: nvidia-gpu
displayName: Nvidia GPUs
description: |
  Monitor Nvidia GPUs based on the Nvidia SMI utility.

install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: nvidia-gpu
        frameworkConfigId: nvidia-gpu
      requiresAccount: false

icon: logo.png

keywords:
  - infrastructure
  - nvidia
  - gpu

categoryTerms:
  - infrastructure
