id: lambdatest
displayName: LambdaTest
description: |
  LambdaTest is an AI-powered test orchestration and execution platform to run manual and automated tests at scale. With LambdaTest, developers and testers can test their websites and mobile applications across 3000+ real browsers, devices, and operating systems.
install:
  primary:
    link:
      url: https://www.lambdatest.com/support/docs/new-relic-integration/
icon: logo.svg
