slug: mux-video
description: |
  ## What is Mux?

  Mux allows users to launch video features in days, customize the player experience, and monitor video streaming performance, all while scaling seamlessly to the world’s largest audiences.
  
  ### Get started!

  The Mux - New Relic integration utilizes Amazon Kinesis Firehose to get data into New Relic. 

  Check out the [documentation](https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/) to learn more about setting up New Relic monitoring for Mux.
summary: |
  Mux provides a platform for your core video infrastructure.
icon: logo.svg
level: New Relic
authors:
  - New Relic (Joseph Counts)
title: Mux (Amazon Firehose)
installPlans:
  - third-party-mux
dataSourceIds:
  - mux-video
dashboards:
  - mux-video-streaming
documentation:
  - name: Mux installation docs
    description: Send Mux logs to New Relic using Amazon Firehose
    url: https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/
keywords:
  - mux
  - video
  - streaming
  - newrelic partner
