slug: mux-video
description: |
  ## What is Mux Data?

  Mux Data is a real-time analytics platform used by some of the largest video brands in the world. Mux Data helps the engineering and operations teams at these companies monitor and improve video streaming performance by measuring the Quality of Experience of every stream: things like startup time, rebuffering, video quality, and playback failure.

  ### Get started!

  The Mux - New Relic integration utilizes Amazon Kinesis Firehose to get data into New Relic. 

  Check out the [documentation](https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/) to learn more about setting up New Relic monitoring for of data from Mux.
summary: |
  Mux Data is a video performance and engagement monitoring platform for developers and publishers of online video.
icon: logo.svg
level: New Relic
authors:
  - New Relic (Joseph Counts)
title: Mux (Amazon Firehose)
installPlans:
  - third-party-mux
dataSourceIds:
  - mux-video
dashboards:
  - mux-video-streaming
documentation:
  - name: Mux installation docs
    description: Send Mux logs to New Relic using Amazon Firehose
    url: https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/
keywords:
  - mux
  - video
  - streaming
  - newrelic partner
