id: 3619a864-7d96-4a6a-9900-758c7e380ec7

slug: elastic-vector-search
description: |
  ## Why should you monitor your usage of Elastic Vector Search?

  Monitor your vector searches on Elastic Vector Search to get visibility on what you send to Elastic Vector Search, responses retrieved from Elastic Vector Search, latency, usage and errors. 

  ### Track the query performance of your Vector DB
  Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.
 
  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.


  ### What’s included in this quickstart?

  Elastic Vector Search uses New Relic Langchain monitoring which provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your Elastic Vector Search app. These reports include:
  
  - Vector searches
  - Alerts for errors, search per vector store, and response time
  - Identify popular queries, sources, and content

summary: |
  Monitor your Vector search's performance and quality with New Relic Elastic Vector Search quickstart.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Elastic Vector Search
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - elastic search
  - elastic vector search
  - vector search
  - dense vector search
  - sparse vector search
  - distributed vector search
  - real-time vector search
  - elasticsearch
  - machine learning
  - artificial intelligence
  - mlops
  - NR1_addData
  - AI
  - ML
  - NLP
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb