
slug: apache-mesos
description: |
  ## Why monitor your Apache Mesos?
  Monitoring Apache Mesos is essential to optimize resource usage and performance in distributed applications, address bottlenecks or failures within the cluster, and facilitate proactive scaling to accommodate evolving workload requirements efficiently.

  ## Comprehensive monitoring quickstart for Apache Mesos
  The Apache Mesos quickstart involves monitoring by tracking master uptime, cluster status, and the statuses of tasks, frameworks, and agents. This comprehensive approach ensures a clear view of system health and performance, facilitating proactive management and rapid issue resolution.

  ## What’s included in the Apache Mesos quickstart?
  New Relic Apache Mesos monitoring quickstart ability to cover quality on out-of-the-box reporting.

  - Dashboards (master uptime, cluster status, tasks status, framework status, agent status and logs)
  - Alerts (error tasks, lost tasks and failed tasks)
  
summary: |
  Gain valuable insights into your Apache Mesos deployment with New Relic's monitoring and analysis capabilities.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Apache Mesos
documentation:
  - name: Apache Mesos integration documentation 
    description: |
      Enhance the performance monitoring and instrumentation of your Apache Mesos by integrating New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/apache-mesos-integration
keywords:
  - Apache Mesos
  - Mesos
  - NR1_addData
  - NR1_sys
dashboards:
  - apache-mesos
alertPolicies:
  - apache-mesos
dataSourceIds:
  - apache-mesos
