
slug: nvml
description: |
  ## Why monitor NVML?
  Monitoring your NVML metrics is crucial to ensure optimal performance, reliability, and efficiency of your GPU-based systems.
  
  ## Comprehensive monitoring quickstart for NVML 
  Monitoring NVML will allow you to effectively track the health and performance of your GPUs, leveraging the capabilities of New Relic for data visualization, alerting, and analysis.

  ## What’s included in this quickstart?
  New Relic NVML monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (power usage, GPU utilisation, clocks, etc)
  - Alerts for NVML (GPU temperature, Power usage)


summary: |
   Monitor and analyze your NVML infrastructure with New Relic.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: NVML
documentation:
  - name: NVML integration documentation
    description: |
      Monitor and instrument your NVML with New Relic to gain deep insights into your performance.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvml-integration/
keywords:
  - NVIDIA
  - NVML
  - GPU Optimization
  - AI Optimization
  - NR1_addData
  - NR1_sys
dataSourceIds:
  - nvml
dashboards:
  - nvml
alertPolicies:
  - nvml