slug: adobe-commerce-business-insights
description: |
  ## Comprehensive monitoring quickstart for Adobe Commerce
  Adobe Commerce involves tracking key performance indicators and other metrics in real-time, to ensure that the system is performing optimally and to identify potential issues before they become major problems.
  ## Why monitor your Adobe Commerce app?
  Adobe Commerce Ecommerce store monitoring is crucial to ensuring that the system is functioning smoothly and providing accurate data insights.
  There are several reasons for this:
  ### Revenue tracking:
  Monitoring Adobe Commerce Ecommerce store allows business owners and ecommerce managers to track revenue performance in real-time, ensuring that sales data is accurate and up-to-date. This information can be critical for making informed decisions around marketing and inventory management.
  ### Downtime impact: 
  A business's revenue can be directly affected by downtime if customers are unable to purchase. Keeping track of downtime and lost revenue can help businesses quantify the impact of these issues.
  ### Order tracking: 
  With Adobe Commerce, businesses can monitor order details such as total orders, average order value, and latest orders in order to get insight into their customer's buying behavior.
  ### Customer details: 
  Analyzing customer details, such as new vs. returning customers and cart abandonment rates, can help businesses better understand their target market.
  ### Funnel monitoring: 
  A funnel monitor tracks and analyzes the behavior of customers as they move through your e-commerce site. By monitoring the funnel, businesses can identify where customers are dropping off and where they need to improve the user experience to drive conversions.
  ## What's included?
  You'll have full-stack observability of your Adobe Commerce app out-of-the-box:
  - Alerts (Downtime (%), HTTP Errors and Largest Contentful Paint (LCP))
  - Dashboards (Executive summary, Customers, Orders, Funnel and more)
  - Keep an eye on the performance and reliability of your Adobe Commerce site
  - Keep track of your transactions and bottom of the funnel on a desktop or mobile device
summary: |
  Adobe Commerce quickstart offers a tailored business insights platform for Adobe Commerce store owners and ecommerce managers. It facilitates real-time data extraction for informed decision-making.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Adobe Commerce Business Insights
documentation:
  - name: Adobe Commerce Business Insights documentation
    description: |
      Adobe Commerce Quickstart provides pre-configured packages for businesses to gain real-time insights.
    url: https://docs.newrelic.com/
keywords:
  - adobe commerce
  - adobe commerce business insights
  - adobe
  - nri-flex
dataSourceIds:
  - new-relic-infrastructure-agent
  - php
  - mysql
  - apache
  - elasticsearch
  - new-relic-synthetics
dashboards:
  - adobe-commerce-business-insights
alertPolicies:
  - adobe-commerce-business-insights
