slug: adobe-commerce-business-insights
description: |
  ## Why monitor your Adobe Commerce website?
  Monitor your Adobe Commerce powered website to ensure that the system is running smoothly. Accurate data insights can help you with:
  - Improved performance: Identify and fix performance bottlenecks, and provide a more responsive shopping experience for your customers.
  - Increased uptime: Detect and resolve issues before they cause downtime. Avoid lost sales and damage to your brand reputation.
  - Enhanced security: Identify & mitigate security threats such as hacking attempts and data breaches, and protect your customers' data & your business's reputation.
  - Better decision-making: Make better decisions about your business, such as how to allocate resources, optimize marketing campaigns, and improve the customer experience.
  - Compliance with regulations: In some industries, such as healthcare and finance, there are strict regulations that businesses must comply with. Monitoring can help you ensure that your application is meeting these regulations.
  
  Overall, monitoring your Adobe Commerce application helps you improve its performance, uptime, security, and decision-making capabilities. This leads to a better shopping experience for your customers, increased sales, and a more secure and compliant business.

  ## Comprehensive monitoring quickstart for Adobe Commerce
  The New Relic Adobe Commerce monitoring quickstart will help businesses and system users track key performance indicators (KPIs) and other metrics in real time. This ensures that the system is performing optimally and helps identify potential issues before they become major problems.
  Below are a few of the key features:
  ### Revenue monitoring:
  Monitoring revenue performance in real time helps ensure the accuracy and timeliness of sales data. Tracking revenue over time to identify trends and patterns, and gain valuable insights to make informed decisions about marketing strategies and inventory management.

  ### Downtime impact: 
  Quantify the impact of downtime on lost revenue.

  ### Order tracking: 
  Keep a close watch on order specifics, including total orders, average order value, and most recent orders, to gain valuable insights into your customers' purchasing patterns.

  ### Customer details: 
  Analyze customer details, such as new vs. returning customers and assessing cart abandonment rates, and gain a deeper understanding of their specific target audience.

  ### Funnel monitoring: 
  Identify the points in the customer journey where you are losing potential customers so that you can make changes to improve the user experience and drive conversions.

  ## What's included?
  You'll have full-stack observability of your Adobe Commerce app out-of-the-box:
  - Alerts (Downtime (%), HTTP Errors and Largest Contentful Paint (LCP))
  - Dashboards (executive summary, customers, orders, funnel, and more)
  - Keep an eye on the performance and reliability of your Adobe Commerce site
  - Keep track of your transactions and bottom of the funnel on a desktop or mobile device

summary: |
  Adobe Commerce quickstart offers a tailored business insights platform for Adobe Commerce store owners and ecommerce managers. It facilitates real-time data extraction for informed decision-making.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Adobe Commerce Business Insights
documentation:
  - name: Adobe Commerce Business Insights documentation
    description: |
      Adobe Commerce Quickstart provides pre-configured packages for businesses to gain real-time insights.
    url: https://docs.newrelic.com/docs/apm/agents/php-agent/other-integrations/magento-business-insights/
keywords:
  - adobe commerce
  - adobe commerce business insights
  - adobe
  - nri-flex
  - adobe magento
  - magento adobe
  - adobe commerce magento
  - adobe magento commerce
  - adobe commerce monitoring
  - adobe commerce business insights
  - ecommerce
  - magento ecommerce
  - adobe ecommerce
  - adobe commerce monitoring
dataSourceIds:
  - new-relic-infrastructure-agent
  - php
  - mysql
  - apache
  - elasticsearch
  - new-relic-synthetics
dashboards:
  - adobe-commerce-business-insights
alertPolicies:
  - adobe-commerce-business-insights
