slug: fivetran-integration
title: Fivetran Destination Monitoring

description: |
  Monitor the status of your Fivetran Connectors to gain visibility on broken connectors.

summary: |
  Monitor Fivetran sync history and detect broken connectors.

level: Community

authors:
  - Michael Young

keywords:
  - fivetran
  - connector
  - pipeline

# Reference to alert policies to be included in this quickstart
alertPolicies:
  - fivetran

# Reference to dashboards to be included in this quickstart
dashboards:
  - fivetran

documentation:
  - name: Fivetran New Relic Setup Guide
    url: https://fivetran.com/docs/logs/external-logs/new-relic/setup-guide
    description: Setup exteral logging with New Relic
