slug: slow-query-analytics
title: Slow Query Analytics
description: |
  This quickstart provides resources to better understand your NRQL query performance.
summary: |
  Find out what kinds of telemetry and query patterns are responsible for slower queries.  The dashbaords in this quickstart will help you pinpoint hot spots and opitimze your queries.
level: New Relic
authors:
  - Marcel Schlapfer
  - Jim Hagan
keywords:
  - NRQL
  - Slow Queries
  - Query Performance
  - Query Optimization
  - Query Timeouts
dataSourceIds:
  - solutions-hub-dashboards
documentation:
  - name: NRQL Query Performance
    url: https://docs.newrelic.com/docs/nrql/nrql-syntax-clauses-functions/
    description: Find slow query patterns and optimize your queries.
icon: logo.svg

dashboards:
  - slow-nrql-queries
