id: onepane
displayName: OnePane
description: |
  OnePane acts as a central hub, bringing together information from various systems like DevOps tools and New Relic. 
  This unified view lets you see how changes and events from these systems correlate with incidents in New Relic, significantly speeding up the process of identifying the root cause (RCA).
icon: logo.png
install:
  primary:
    link:
      url: https://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment
keywords:
  - devops
  - change tracking
  - incident correlation
  - root cause analysis
  - llm
categoryTerms:
  - logs
  - newrelic partner
  - generative ai
  - azure
  - aws
  - kubernetes
  - containers
  - infrastructure
