id: onepane
displayName: Onepane
description: Connect Onepane change tracking and automated RCA to New Relic
icon: logo.png
install:
  primary:
    link:
      url: https://www.onepane.ai/docs/en/articles/8999270-adding-onepane-change-tracking-to-your-new-relic-deployment
keywords:
  - devops
  - change tracking
  - incident correlation
  - root cause analysis
  - llm
categoryTerms:
  - logs
  - newrelic partner
  - generative ai
  - azure
  - aws
  - kubernetes
  - containers
  - infrastructure
