id: databricks
displayName: Databricks Integration
description: |
  Databricks is an orchestration platform for Apache Spark. Instantly monitor Databricks Spark applications with our New Relic Spark integration. Easily track the health of your Databricks clusters, fine-tune your Spark jobs for peak performance, and troubleshoot problems with this integration.
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/newrelic-experimental/newrelic-databricks-integration
keywords:
  - nrlabs
  - nrlabs-data
  - apache spark
  - spark
  - databricks
  - newrelic partner
categoryTerms:
  - newrelic partner
