id: zipkin
displayName: Zipkin
description: You can send your Zipkin-formatted traces to New Relic via the Trace API. Once your Zipkin data is in New Relic, you can use our UI tools to analyze your traces.
install:   
  primary:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: zipkin
    requires_account: false
icon: logo.svg
