id: 24da1e3a-035d-493c-a881-72c42b601027
slug: full-stack-observability
title: Full Stack Observability
description: |
  Set of dashboards with data from all New Relic Products, giving you Full Stack Observability over Metrics, Events, Logs and Traces.
summary: |
  Full Stack Observability over Metrics, Events, Logs and Traces.
level: New Relic
icon: logo.svg
website: https://www.newrelic.com/
authors:
  - New Relic
  - Samuel Vandamme
installPlans:
  - guided-install
dataSourceIds:
  - guided-install
keywords:
  - full stack observability
  - NR1_addData
  - NR1_sys
dashboards:
  - full-stack-observability

documentation:
  - name: Guild installation documentation
    description: Monitor your Full Stack with New Relic.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview/

