id: c264449d-e7a1-4497-9b73-df1bdfe79f82

slug: docarray-inmemorysearch
description: |
  ## Why should you monitor your usage of Doc Array InMemorySearch?

  Monitor your vector searches on Doc Array InMemorySearch to get visibility on what you send to Doc Array InMemorySearch, responses retrieved from Doc Array InMemorySearch, latency, usage and errors. 

  ### Track the query performance of your Vector DB
  Track the behavior of your vector stores. Monitor the latency, queries, the number of documents retrieved, and the content of the documents so that you can evaluate their relevance.
 
  ### Track your app:  
  By tracking key metrics like latency, throughput, error rates, and input & output, you can gain insights into your app's performance and identify areas of improvement.


  ### What’s included in this quickstart?

  New Relic LangChain monitoring quickstart provides a variety of pre-built dashboards, which will help you gain insights into the health and performance of your LangChain app. These reports include:
  
  - Vector searches
  - Alerts for errors, search per vector store, and response time
  - Identify popular queries, sources, and content

summary: |
  Monitor your Vector search's performance and quality with New Relic Doc Array InMemorySearch quickstart.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Doc Array InMemorySearch
documentation:
  - name: LangChain Vector Database integration documentation
    description: |
      Implement monitoring and instrumentation for your Vector store, and ensure that your observability data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - doc array
  - vector search
  - in memory search
  - in-memory search
  - in memory
  - document search
  - multimodal search
  - open source
  - python
  - machine learning
  - artificial intelligence
  - AI
  - ML
  - NLP
  - mlops
  - NR1_addData
dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb