id: confluent-cloud
displayName: Confluent Cloud
description: Observability for Confluent Cloud's fully managed service for Apache Kafka delivered using an OpenTelemetry Collector.
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/other-examples/collector/confluentcloud
keywords:
  - Confluent
  - Confluent Cloud
  - Metrics
  - OTel
  - OpenTelemetry
  - open telemetry
  - OTelCol
  - OpenTelemetry Collector
  - open telemetry collector
  - Collector
  - Kafka
categoryTerms:
  - infrastructure
