id: 9c559112-90e1-4ff4-b38b-90c0ba3c56fe

# Name of the quickstart
name: kafka

# Title of the quickstart
title: Kafka

# Description of the quickstart
description: |+
  Official New Relic quickstart for Kafka
  Use this quickstart together with the New Relic Kafka On Host Integration to get insight into the performance of your Kafka cluster.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://kafka.apache.org/

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak

documentation:
  - name: Kafka
    description: >-
      Distributed streaming platform built for scalability, fault-tolerance, and building real-time data pipelines and streaming applications.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration/

installPlans:
  - infra-agent-targeted
  - kafka-integration-docs
