# Sets the URL name of the quickstart on public I/O (required)
slug: dbt-cloud 

# Displayed in the UI (required)
title: dbt Cloud

# Long-form description of the quickstart (required)
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. Our dashboard and alerts help you find issues with dbt Cloud runs and resources (models, seeds, snapshots, tests). Includes the ability to collect failed test rows from dbt tests in Snowflake.

summary: |
  dbt Cloud integration using an Airflow DAG.
# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Leo Godin 

# Keywords for filtering / searching criteria in the UI
keywords:
  - dbt cloud 
  - dbt

dataSourceIds:
  - dbt-cloud

# Reference to alert policies to be included in this quickstart
alertPolicies:
  - dbt-cloud

# Reference to dashboards to be included in this quickstart
dashboards:
  - dbt-cloud 

# Documentation references
documentation:
  - name: dbt cloud integration documentation 
    description: |
      Installation documentation for dbt Cloud observability using an Airflow DAG
    url: >-
      https://docs.newrelic.com/docs/more-integrations/dbt-cloud/dbt-cloud-integration/
  - name: Git repository
    description: |
      Git repository for the Airflow DAG and additional documentation
    url: >-
      https://github.com/newrelic-experimental/newrelic-dbt-cloud-integration    

# Content / Design
icon: logo.png
website: https://www.getdbt.com/ 