slug: dbt-cloud
description: |
  Integrates dbt Cloud with New Relic using an Airflow DAG. Our dashboard and alerts help you find issues with dbt Cloud runs and resources (models, seeds, snapshots, tests). Includes the ability to collect failed test rows from dbt tests in Snowflake.

summary: |
  dbt Cloud integration using an Airflow DAG.
icon: logo.png
level: Community
authors:
  - New Relic
  - Leo Godin
title: dbt Cloud

keywords:
  - dbt cloud
  - dbt
dashboards:
  - dbt-cloud
alertPolicies:
  - dbt-cloud
dataSourceIds:
  - dbt-cloud
