# A unique identifier for the data source
id: rafay

# Display name for the data source
displayName: Rafay

description: |
  Monitor Multiple K8's Clusters with Rafay

install:
  primary:
    link: https://docs.rafay.co/recipes/monitoring/newrelic/

# An icon for display within the catalog
icon: logo.svg

# Searchable words or phrases
keywords:
  - rafay
  - k8s
  - kubernetes
  - cluster
  - multi-cluster
  - newrelic partner
