id: apm-signals
displayName: APM Signals
description: |
  Comprehensive APM dashboard providing actionable insights, including Throughout, Latency, Error Rate & Apdex. 
  primary:
    link:
      url: https://newrelic.com/blog/best-practices/monitoring-golden-signals
icon: logo.svg
