id: redmine
displayName: Redmine monitoring
description: |
  New Relic’s instant observability Redmine quickstart helps you get full visibility into the into the performance of your Redmine app.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: redmine
      requiresAccount: false
icon: logo.png
