slug: qdrant
description: |
  ## Why should you monitor Qdrant?
  Monitoring Qdrant is essential to maintaining its performance, reliability, and security, especially in applications.

  ## Comprehensive monitoring quickstart for Qdrant
  Monitoring MosaicML helps you ensure that your models are training and performing as expected, track their progress over time, identify potential bottlenecks, troubleshoot problems, and comply with regulations.

  ## What’s included in the Qdrant quickstart?
  New Relic Qdrant monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (response time, searches by provider, document retrieved and etc)
  - Alerts (errors, and response time)
summary: |
  By integrating with New Relic, you can get comprehensive application monitoring and optimization for your Qdrant applications.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Qdrant
documentation:
  - name: Qdrant integration documentation
    description: |
      Implement monitoring and instrumentation for your Qdrant, and ensure that your Qdrant data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - qdrant
  - vector database
  - mlops
  - machine learning
  - artificial intelligence
  - ai
  - NR1_addData

alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb