slug: ray
description: |
  ## Comprehensive monitoring quickstart for Ray
  By integrating Ray with New Relic, you can get comprehensive information about the quality of your codebase and receive alerts about serious vulnerabilities. Enabling you to effectively monitor performance, promptly diagnose issues, and optimize your application for improved efficiency and scalability.

  ## Why monitor Ray?
  Monitoring your Ray with New Relic, you gain comprehensive visibility and insights into your Ray environment. This empowers you to optimize performance, troubleshoot issues effectively, and ensure the reliability and scalability of your applications.


  ## What’s included in this quickstart?
  New Relic Ray monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (Active nodes, Status code and Scheduler tasks)
  - Alerts (Active nodes, Free disk percentage and RPC health check latency)
summary: |
  Identify and optimize Ray performance with New Relic Ray monitoring.
icon: logo.svg
level: New Relic
authors:
  - New Relic
  - Praveen Kudikyala
title: Ray
documentation:
  - name: Ray integration documentation 
    description: |
      Monitor the performance metrics of your Ray instances in real-time with New Relic Ray.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ray-integration/
keywords:
  - ray
  - python
  - python3
  - mlops
  - ai
  - generative ai
  - machine learning
  - artificial intelligence
  - NR1_addData
  - NR1_sys
dashboards:
  - ray
alertPolicies:
  - ray
dataSourceIds:
  - ray