
slug: wordpress-fullstack
description: |
  ## Comprehensive monitoring quickstart for WordPress
  WordPress is an open source software used for creating a website, blog, or app. It is a content management system with a plugin architecture and a template system known as Themes. New Relic WordPress Full Stack quickstart empowers you to monitor the performance metrics of your WordPress application by installing agents and configuring nri-flex on your host.
  
  ### Why monitor WordPress?
  WordPress applications are widely used to create websites of all different types of domains. Being so flexible, these websites can also get slowed down due to multiple factors. Some factors include plugins which take a lot of time to load, in some cases, there could be database connection issues or could be any other factors.
  By using our WordPress Full Stack quickstart, we are providing you with documentation on the steps which are to be followed to instrument the quickstart and also a pre-build dashboard to check all the key performance metrics, database metrics and error messages which are triggered on a specific URL. Once these indicators are seen, it would help you and your team of developers to understand the concern and implement the right solution which in return improves your website performance.

  ### What’s included in this quickstart?
  New Relic WordPress Full Stack monitoring agent capture the following metrics:
  - User usage statistics
  - Database metrics like connections per second and more
  - Browser metrics like page view comparison, TTFB and more
  - Transactions and its error messages
  - Plugin related metrics to understand the most time consuming plugin
  - Wordpress debug logs are also captured
summary: |
  WordPress Full Stack comes with a pre-build dashboard which helps in monitoring and understanding key metrics of your application.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: WordPress Full Stack
documentation:
  - name: WordPress Full Stack documentation
    description: |
      Monitor the performance metrics of your WordPress application and its instances in real-time with New Relic.
    url: https://docs.newrelic.com/
keywords:
  - wordpress
  - php
  - performance monitoring
  - CMS
  - wordpress full stack
  - browser
  - full stack
dataSourceIds:
  - new-relic-infrastructure-agent
  - php
  - mysql
  - apache
dashboards:
  - wordpress-fullstack
alertPolicies:
  - wordpress-fullstack
