id: xmatters
displayName: xMatters
description: |
  Set up automated alerts for detecting and responding to events and critical issues in xMatters and send your data to New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#xMatters_templates
icon: logo.svg
