id: temporal
displayName: Temporal
description: |
  Optimize your Temporal performance using New Relic Temporal monitoring.
icon: logo.svg
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration/
keywords:
  - temporal
  - temporal web host
  - temporal java sdk
  - workflow
  - cluster