id: 
slug: newrelic-java-vertx
title: New Relic Java Instrumentation for Vert.x Event Bus
description: |
  # What is Vert.x?
  Vert.x, a reactive, event-driven framework for the JVM, empowers building high-performance, 
  scalable apps with minimal resources. Its toolkit supports diverse use cases including web apps, 
  microservices, and IoT solutions.

summary: |
  Provides instrumentation for monitoring the Vert.x Event Bus. Tracks flow across the event bus.
  Vertx-Verticles provides instrumentation for classes extends AbstractVerticle. It does this by 
  instrumenting each class that is deployed. 
  It tracks all methods except those defined by AbstractVerticle. 
  Methods not tracked: start, stop, rxStart, rxStop, config, deploymentID, getVertx, init, processArgs.

level: Community

keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - eventbus

icon: vertx.svg
authors:
  - New Relic Labs
dataSourceIds:
  - newrelic-java-vertx
documentation:
  - name: New Relic Java Instrumentation for Vert.x Event Bus
    description: |
      Provides instrumentation for Java Instrumentation for Vert.x Event Bus.
    url: https://github.com/newrelic/newrelic-java-vertx/tree/main#installation

dashboards:
  - java
alertPolicies:
  - java
