slug: temporal
description: |
  ## Comprehensive monitoring quickstart for Temporal
  The Temporal web provides users with workflow execution state and metadata for debugging purposes. Integrating Temporal with New Relic allows you to leverage the strengths of both systems, enabling a holistic monitoring solution encompassing metrics, traces, logs, and alerts. Customize the outlined steps according to the specific programming language and framework employed in your Temporal services.
  
  ## Why monitor Temporal?
  Monitoring allows you to identify performance bottlenecks, such as slow workflows or inefficient resource usage, and optimize your Temporal application for better performance and helps you detect and diagnose faults or errors in your Temporal workflows.

  ## What’s included in this quickstart?
  New Relic Temporal monitoring quickstart provides quality out-of-the-box reporting:

  - Cluster metrics
  - Queue metrics
  - Java SDK metrics
  - Infrastructure metrics
  - Dashboards
  - Alerts
  
summary: |
  Monitor and analyze your Temporal web with New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Temporal
documentation:
  - name: Temporal integration documentation 
    description: |
      Enhance the performance monitoring and instrumentation of your Temporal by integrating New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration/
keywords:
  - temporal
  - temporal web host
  - temporal java sdk
  - workflow
  - cluster
  - NR1_Adddata
dashboards:
  - temporal
alertPolicies:
  - temporal
dataSourceIds:
  - temporal
