id: mevn-stack
displayName: MEVN Stack Integration
description: |
  Monitor your apps using New Relic MEVN integration with Vue, MongoDB and NodeJS agents for browser, database and application monitoring.

install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/browser/browser-integrations/mexn-integration/

icon: logo.png

keywords:
  - MEVN
  - MongoDB
  - ExpressJS
  - Vue
  - NodeJS
  - Fullstack
