slug: weaviate
description: |
  ## Why should you monitor Weaviate?
  By using the Weaviate quickstart, you will be able to:
  ### Ensure availability and performance: 
  Monitoring Weaviate identifies and fixes any issues that may affect its availability or performance.
  ### Detects security threats: 
  Monitoring Weaviate detects any security threats that may be targeting your data and help you to protect your data from unauthorized access or misuse.
  ### Troubleshoot problems:
  Monitoring Weaviate will help you to troubleshoot the issue and take corrective action.

  ## Comprehensive monitoring quickstart for Weaviate
  Monitoring Weaviate is a critical task that can help you ensure the availability, performance, security, and compliance of your database.

  ## What’s included in the Weaviate quickstart?
  New Relic Weaviate monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your Weaviate. These reports include:
  - Dashboards (average tokens, LLM completion’s details, chain’s details, tool details, top tool names and many more)
  - Alerts (errors, request per model and response time)
summary: |
  Improve your Weaviate performance with New Relic Weaviate quickstart.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Weaviate
documentation:
  - name: Weaviate integration documentation
    description: |
      Implement monitoring and instrumentation for your Weaviate, and ensure that your Weaviate's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain-vectordb
keywords:
  - weaviate
  - weaviate ai
  - mlops
  - large language model
  - natural language processing
  - machine learning
  - artificial intelligence
  - ai
  - generative ai
  - graph database

alertPolicies:
  - langchain-vectordb
dashboards:
  - langchain-vectordb
