slug: pytorch
description: |
  ## Why monitor your PyTorch app?
  PyTorch is an open source machine learning library used for developing and training neural network based deep learning models. New Relic PyTorch quickstart performance monitoring offers immediate and pre-configured observability.
  With this quickstart, you will:
  ### Ensure Output Quality:
  PyTorch is a powerful tool for deep learning, but it can be difficult to ensure that the output of your models is accurate and reliable. By monitoring your app, you will identify any problems with the output and take steps to correct them.
  ### Troubleshoot Problems:  
  If your app is not working as expected, using the monitoring data to troubleshoot the problem helps identify the source of the issue and take corrective action.
  ### Identify and Rectify Errors: 
  PyTorch apps are complex and can be prone to errors. By monitoring your app, you will identify any errors that occur and take steps to fix them.
  
  ## Comprehensive monitoring quickstart for PyTorch
  With the help of PyTorch quickstart, you can effectively monitor your PyTorch application, gain insights into its performance, and ensure it operates smoothly, securely, and efficiently, particularly in machine learning and deep learning applications.
  
  ## What’s included in the PyTorch quickstart?
  New Relic PyTorch monitoring quickstart provides quality out-of-the-box reporting:
  - Real-time visibility: Get insights into the performance of your PyTorch application in real time
  - Security insights: Get insights into the security of your PyTorch application and identify potential threats
  - Be proactively alerted about critical issues related to your app's status
  - Gain code-related insights about your app's health and status
summary: |
  Use New Relic quickstart to monitor and analyze your PyTorch application.
icon: logo.png
level: 
  - New Relic
  - Jyothi Surampudi
authors:
  - New Relic
title: PyTorch
documentation:
  - name: PyTorch integration documentation
    description: |
     Implement monitoring and instrumentation for your PyTorch application, and ensure that your application's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  pytorch
  -  pytorch ai
  -  torch
  -  py torch
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence