slug: pytorch
description: |
  ## Why should you monitor PyTorch?
  PyTorch is an open source machine learning library used for developing and training neural network based deep learning models. New Relic PyTorch quickstart performance monitoring offers immediate and pre-configured observability.
  By using the PyTorch quickstart, you will be able to:
  ### Identify performance bottlenecks: 
  Improve the performance of your PyTorch by optimizing the code.
  ### Ensure output quality:
  Identify problems with the output of your model and take corrective steps.
  ### Error identification and resolution:
  Monitoring enables prompt error identification, preventing future occurrences and ensuring PyTorch's health and reliability.
  ## Comprehensive monitoring quickstart for PyTorch
  With the help of PyTorch quickstart, you can effectively monitor your PyTorch, gain insights into its performance, and ensure it operates smoothly, securely, and efficiently, particularly in machine learning and deep learning applications.
  
  ## What’s included in the PyTorch quickstart?
  New Relic PyTorch monitoring quickstart provides quality out-of-the-box reporting:
  - Real-time visibility: Get insights into the performance of your PyTorch in real time
  - Security insights: Get insights into the security of your PyTorch and identify potential threats
  - Be proactively alerted about critical issues related to the PyTorch status
  - Gain code-related insights about the PyTorch health and status
summary: |
  Use New Relic quickstart to monitor and analyze your PyTorch.
icon: logo.png
level: 
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: PyTorch
documentation:
  - name: PyTorch integration documentation
    description: |
     Implement monitoring and instrumentation for your PyTorch, and ensure that your PyTorch data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  pytorch
  -  pytorch ai
  -  torch
  -  py torch
  -  python
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence