slug: pytorch
description: |
  ## Why should you monitor PyTorch?
  PyTorch is an open source machine learning library used for developing and training neural network based deep learning models. New Relic PyTorch quickstart performance monitoring offers immediate and pre-configured observability.
  By using the PyTorch quickstart, you will be able to:
  ### Identify performance bottlenecks: 
  Monitoring PyTorch can help you identify performance bottlenecks. This can help you improve the performance of your PyTorch by optimizing the code.
  ### Ensure output quality:
  PyTorch is a powerful tool for deep learning, but it can be difficult to ensure that the output of your models is accurate and reliable. By monitoring your PyTorch, you will identify any problems with the output and take steps to correct them.
  ### Detecting errors: 
  Monitoring PyTorch can help you detect errors. This can help you fix the errors and prevent them from happening again.
  ### Preventing outages: 
  Monitoring PyTorch can help you prevent outages. This can be done by monitoring the health of the PyTorch and taking action if any problems are detected.
  
  ## Comprehensive monitoring quickstart for PyTorch
  With the help of PyTorch quickstart, you can effectively monitor your PyTorch, gain insights into its performance, and ensure it operates smoothly, securely, and efficiently, particularly in machine learning and deep learning applications.
  
  ## What’s included in the PyTorch quickstart?
  New Relic PyTorch monitoring quickstart provides quality out-of-the-box reporting:
  - Real-time visibility: Get insights into the performance of your PyTorch in real time
  - Security insights: Get insights into the security of your PyTorch and identify potential threats
  - Be proactively alerted about critical issues related to the PyTorch status
  - Gain code-related insights about the PyTorch health and status
summary: |
  Use New Relic quickstart to monitor and analyze your PyTorch.
icon: logo.png
level: 
  - New Relic
  - Jyothi Surampudi
authors:
  - New Relic
title: PyTorch
documentation:
  - name: PyTorch integration documentation
    description: |
     Implement monitoring and instrumentation for your PyTorch, and ensure that your PyTorch data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  pytorch
  -  pytorch ai
  -  torch
  -  py torch
  -  python
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence