
# Name of the pack
name: Gatsby Build

# Description of the pack
description: |+

  # This is a header
  ## This is also a header

  - bullet 1
  - bullet 2

  1. number 1
  2. number 2

  **bold**
  *italic*

  The Gatsby observability pack allows you to get visibility into the build time of your Gatsby Sites,
  using [Open Telemetry](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/introduction-opentelemetry-new-relic/)
  to collect each step as a span in a Distributed Trace. This Dashboard lets you monitor your build in real-time to highlight which steps are affecting performance,
  so you can improve them faster.


# Support level: New Relic | Verified | Community
level: New Relic

# Design
icon: icon.png
logo: logo.png

# Authors of the pack
authors:
  - New Relic
  - Ruairi Douglas
