id: infrastructure-signals
displayName: Infrastructure Signals
description: |
  Comprehensive Infrastructure dashboard providing actionable insights, including CPU Usage. Storage Usage, Network Traffic & Memory Usage. 
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/infrastructure-ui-pages/infra-ui-overview/
icon: logo.svg
