id: mobile-signals
displayName: Mobile Signals
description: |
  New Relic's mobile monitoring capabilities provide deeper visibility into the performance and crash troubleshooting of your Android, iOS, or hybrid mobile applications. 
  install:
   primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring/
icon: logo.svg
