# A unique identifier for the data source
id: webhook-notifications

# Display name for the data source
displayName: Webhook Notifications

description: |
  Ready to integrate Webhook with New Relic? Check out our documentation to learn how to set up a Webhook workflow from New Relic.

install:
  primary:
    link: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#webhook

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - webhook
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations
