id: langchain-vectordb
displayName: LangChain Vector Database
description: |
  Implement monitoring and instrumentation for your LangChain Vector Database and ensure that your vector database is integrated into New Relic for effective performance analysis and insights.
install:
  primary:
    link:
      url: https://github.com/newrelic/nr-openai-observability
icon: logo.png
keywords:
  -  langchain vector database
  -  langchain ai
  -  lang
  -  chain
  -  ai
  -  lang chain
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence