id: windows-certs
displayName: Flex Windows Cert Expiration Monitoring Install Plan
description: |
  Using the infrastructure agent and a flex integration you can pull certification expiration using powershell and send the information to new relic to be used in dashboards or alerts.

  Follow the regular flex installation process to add this flex integration to your agents, study the data to confirm if it matches your needs. 
icon: logo.png   
# Searchable words or phrases
keywords:
  - os
  - windows
  - certs
  - certificates

install:
  primary: 
    link:
      url: https://github.com/newrelic/nri-flex/tree/master/examples/windows/WindowsExpCertSample

categoryTerms:
  - infrastructure
