id: 816e3eba-ffea-4b0c-9150-b7a0f3a025d9

# Name of the quickstart
name: lamp-stack

# Title of the quickstart
title: LAMP stack

# Description of the quickstart
description: |+
  This LAMP quickstart allows you to monitor a LAMP stack (Linux, Apache, MySQL, PHP).
  It includes a specific dashboard to get observability for an entire LAMP stack.

  NOTE: Quickstart references are currently not yet implemented,
  this means you will have to install the Apache, MySQL and PHP quickstart to get those dashboards and alerts.

# Support level
level: New Relic

# Authors of the quickstart
authors:
  - New Relic
  - Stijn Polfliet

installPlans:
  - mysql-integration
  - apache-integration
  - php-agent
