# A unique identifier for the data source
id: hcp-envoy

# Display name for the data source
displayName: HCP Envoy

description: |
  Report HCP Envoy metrics to New Relic via New Relic's statsd integration.

install:
  primary:
    link:
      url: https://github.com/newrelic-experimental/hashicorp-quickstart-annex/tree/main/hcp-envoy/README.md

# An icon for display within the catalog
icon: logo.svg

# Searchable words or phrases
keywords:
  - hcp
  - hcp-envoy
  - hashicorp
  - envoy
  - envoy-proxy
  - nrlabs
  - nrlabs-data
