slug: openstack-controller
description: |
  ## Comprehensive monitoring quickstart for Openstack Controller
  The OpenStack controller ensures the health, performance, and availability of your cloud infrastructure by monitoring various services and components.

  ## Why monitor Openstack Controller?
   Monitoring the OpenStack controller helps you maintain the stability, performance, security, and availability of your cloud environment by detecting issues early, responding promptly, and continuously improving your infrastructure to meet the needs of users and applications.

  ## What’s included in this quickstart?
  New Relic Openstack Controller monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (Events, Projects, Networks, Domains, etc)

summary: |
   Use New Relic to monitor and analyze your Openstack Controller infrastructure.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Openstack Controller
documentation:
  - name: Openstack Controller integration documentation
    description: |
      Implement monitoring and instrumentation for your Openstack Controller, and ensure that your Openstack data is integrated into New Relic for effective performance analysis and insights.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/openstack-controller-integration/
keywords:
  - openstack controller
  - openstack
  - nova controller
  - neutron controller
  - cinder controller
  - Keystone controller
dataSourceIds:
  - openstack-controller
dashboards:
  - openstack-controller