id: temporal-cloud
displayName: Temporal cloud
description: |
  Optimize your Temporal cloud performance using New Relic Temporal cloiud monitoring.
icon: logo.svg
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/temporal-cloud-integration/
keywords:
  - temporal
  - temporal cloud
  - temporal java sdk
  - workflow
  - cluster