id: temporal-cloud
displayName: Temporal cloud
description: |
  Optimize your Temporal cloud performance using New Relic Temporal cloud monitoring.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: temporal-cloud
        frameworkConfigId: temporal-cloud
      requiresAccount: false
keywords:
  - temporal
  - temporal cloud
  - temporal java sdk
  - workflow
  - cluster