id: kentik
displayName: Kentik Firehose
description: |
  This integration gives you visibility into data ingested via the Kentik Firehose. The data is sent to Kentik and enriched before being sent to New Relic.
  The data from Kentik Firehose provides insights into Network Flows, Network Synthetics, and performance telemetry associated with Kentik-monitored devices.
icon: logo.png
install:
  primary:
    link:
      url: https://kb.kentik.com/v0/Fc19.htm#Fc19-Firehose_Overview
keywords:
  - kentik
  - firehose
  - network
  - NPM
  - Synthetics
  - NetFlow
  - sFlow
  - JFlow
  - IPFIX
  - newrelic partner
categoryTerms:
  - newrelic partner
  - synthetics
  - network
