id: amazon-workmail
displayName: Amazon WorkMail
description: Monitor Amazon WorkMail by sending metrics to New Relic
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-workmail-monitoring-integration/
icon: logo.png