slug: langchain
description: |
  ## Why monitor LangChain?
  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
  By using the LangChain quickstart, you will be able to:
  ### Ensure uptime: 
  LangChain AI is a complex system, and it is important to make sure that it is always up and running. By monitoring the system, you will quickly identify and fix any issues that may cause downtime.
  ### Track performance:  
  Monitoring the performance of LangChain AI will help you identify areas where you will improve. For example, you will track things like latency, throughput, and error rates.
  ### Improve the model: 
  Monitoring the performance of LangChain AI allows for the identification of areas where the model can be improved. For example, tracking the accuracy of the model's predictions and the diversity of the model's responses.
  
  ## Comprehensive monitoring quickstart for LangChain
  Our LangChain quickstart provides metrics, including uptime, accuracy, relevance, and speed. These metrics serve as valuable tools to empower you in maximizing the performance of LangChain AI.
  
  ## What’s included in this quickstart?
  New Relic LangChain monitoring quickstart offers a range of out-of-the-box reports, including:
  - Gain code-related insights about your LangChain's health and status
  - Monitor your LangChain latency and transactions
  - Dashboard (average tokens, cost, total requests, api response time and many more)
  - Alerts (errors,requests per model and response time)
summary: |
  Use the New Relic LangChain quickstart to improve the performance of your LangChain.
icon: logo.png
level: 
  - New Relic
  - Jyothi Surampudi
authors:
  - New Relic
title: LangChain
documentation:
  - name: LangChain integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain, and ensure that your LangChain data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  -  llm-application 
keywords:
  -  langchain
  -  langchain ai
  -  lang
  -  chain
  -  ai
  -  lang chain
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence
alerts:
  langchain  