slug: langchain
description: |
  ## Why monitor LangChain?
  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
  By using the LangChain quickstart, you will be able to:
  ### Ensure uptime: 
  LangChain AI is a complex system, and it is important to make sure that it is always up and running. By monitoring the system, you will quickly identify and fix any issues that may cause downtime.
  ### Track performance:  
  By tracking key metrics like latency, throughput, and error rates, you can gain insights into LangChain AI's performance and identify areas of improvement.
  ### Improve the model: 
  Monitoring the performance of LangChain AI allows for the identification of areas where the model can be improved. For example, tracking the accuracy of the model's predictions and the diversity of the model's responses.
  
  ## Comprehensive monitoring quickstart for LangChain
  Our LangChain quickstart provides metrics, including uptime, accuracy, relevance, and speed. These metrics serve as valuable tools to empower you in maximizing the performance of LangChain AI.
  
  ## What’s included in this quickstart?
  New Relic LangChain monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your LangChain. These reports include:
  - Code-related insights to identify potential problems with your code and improve its performance
  - Latency details and number of tokens
  - Entity details such as the average number of tokens used, the cost per entity, and the total number of requests made
  - Alerts for errors,requests per model and response time
summary: |
  Improve your LangChain Performance with New Relic LangChain Quickstart.
icon: logo.png
level: 
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: LangChain
documentation:
  - name: LangChain integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain, and ensure that your LangChain data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  -  langchain
keywords:
  -  langchain
  -  langchain ai
  -  lang
  -  chain
  -  ai
  -  lang chain
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence
  -  NR1_addData 
alerts:
  langchain  