slug: langchain
description: |
  ## Why monitor LangChain?
  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
  With this quickstart, you will:
  ### To ensure uptime: 
  LangChain AI is a complex system, and it is important to make sure that it is always up and running. By monitoring the system, you will quickly identify and fix any issues that may cause downtime.
  ### To track performance:  
  Monitoring the performance of LangChain AI will help you identify areas where you will improve. For example, you will track things like latency, throughput, and error rates.
  ### To improve the model: 
  By monitoring the performance of LangChain AI, you will identify areas where the model will be improved. For example, you will track things like the accuracy of the model's predictions and the diversity of the model's responses.
  
  ## Comprehensive monitoring quickstart for LangChain
  Our LangChain quickstart provides you metrics such as uptime, accuracy, relevance, and speed. These metrics can help you ensure that LangChain AI is performing at its best.  
  
  ## What’s included in this quickstart?
  New Relic LangChain monitoring quickstart provides quality out-of-the-box reporting:
  - Gain code-related insights about your app's health and status
  - Monitor your LangChain latency and transactions
  - Be proactively alerted about critical issues related to your app's status
  - Dashboard (average tokens, cost, total requests, api response time and many more)
summary: |
  Use the New Relic LangChain quickstart to improve the performance of your LangChain application.
icon: logo.png
level: 
  - New Relic
  - Jyothi Surampudi
authors:
  - New Relic
title: LangChain
documentation:
  - name: LangChain integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain application, and ensure that your application's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  langchain
  -  langchain ai
  -  lang
  -  chain
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence