slug: langchain
description: |
  ## Comprehensive monitoring quickstart for LangChain
  Monitoring LangChain with our quickstart shows you performance metrics and inventory data on a real-time basis, create your own custom dashboard with charts and queries, and create alert policies.
  ## Why monitor LangChain
  LangChain is a framework for developing applications powered by language models. New Relic LangChain quickstart performance monitoring offers immediate and pre-configured observability.
  With this quickstart, you can:
  ### Resource Management: 
  Effective monitoring ensures efficient resource allocation. You can monitor gas consumption, memory usage, CPU utilization, and disk space to prevent resource exhaustion and downtime.
  ### Performance Optimization: 
  Monitoring helps you identify and address performance bottlenecks, improving the efficiency of your LangChain application. 
  ### User experience: 
  Monitoring the framework can help you identify areas for improvement in your application's user experience and make informed decisions about how to optimize it for your users.
  ## What’s included in this quickstart?
  New Relic LangChain monitoring quickstart provides quality out-of-the-box reporting:
  - Gain code-related insights about your app's health and status.
  - Monitor your LangChain latency and transactions. 
  - Be proactively alerted about critical issues related to your app's status.
  - Monitor your app's custom metrics. 
  - Dashboard (average tokens, cost, total requests, api response time and many more)
summary: |
  Explore the LangChain Framework, understand the significance of monitoring LangChain, discover the essential features of a LangChain monitoring tool, and uncover the distinct advantages offered by the LangChain quickstart.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: LangChain
documentation:
  - name: LangChain integration documentation
    description: |
    Implement monitoring and instrumentation for your LangChain application, and ensure that your application's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  langchain
  -  machine learning
  -  artificial intelligence