id: ad9f635b-6496-48a8-b373-9fab81a7f719
# Name of the quickstart
name: mysql

# Title of the quickstart
title: MySQL

# Description of the quickstart
description: |+
  Official New Relic quickstart for MySQL and MariaDB
  Use this quickstart together with the New Relic MySQL On Host Integration to get insight into the performance of your MySQL and MariaDB instances.

# Support level
level: New Relic

# Design
logo: logo.png
website: https://en.wikipedia.org/wiki/MySQL

# Authors of the quickstart
authors:
  - New Relic

documentation:
  - name: MySQL
    description: >-
      Open source relational database with more than 20 years of community development and support.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration/

installPlans:
  - mysql-integration

keywords:
  - infrastructure
  - database
