id: amazon-cloudwatch-metric-streams
displayName: Amazon CloudWatch Internet Monitor
description: |
  Amazon CloudWatch Internet Monitor how internet issues impact the performance and availability between your applications hosted on AWS and your end users
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream/
keywords:
  - aws
  - cloudwatch
  - amazon web services
  - cloudwatch internet monitor
icon: logo.svg
