id: mssql-customqueries
displayName: MSSQL On-Host Integration w/ Custom Queries
description: |
  Display MSSQL information collected from custom queries
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration/
icon: logo.svg