# A unique identifier for the data source
id: skykit

# Display name for the data source
displayName: Skykit Dashboards

description: |
  Display New Relic dashboards anywhere for the entire company to see.

install:
  primary:
    link:
      url: https://www.skykit.com/products/dashboards/connections/new-relic/

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - cms
  - content management system
  - newrelic partner
