
slug: apache-zooKeeper
description: |
  ## Comprehensive monitoring quickstart for Apache zooKeeper
  New Relic detects your Apache ZooKeeper metrics like znode count, watch count, client connections, etc.  Monitor your zooKeeper ensemble, ensuring optimal performance and troubleshooting issues in a timely manner.

  ## Why monitor Apache ZooKeeper?
   By leveraging Apache ZooKeeper monitoring by New Relic, you gain invaluable visibility into the overall health and performance of your distributed system. This empowers you to swiftly identify and address any potential issues, ensuring optimal operational efficiency.

  ## What’s included in this quickstart?
  With Apache ZooKeeper monitoring quickstart by New Relic, you can instantly achieve comprehensive observability across your entire stack, right from the start:
  - Dashboards (ZNode count, watch count, max latency, client connections, etc)
  - Alerts for zookeeper (Rejected Connection, Changed watch node)

summary: |
   Unlock the power of Apache ZooKeeper monitoring with the seamless integration of New Relic infrastructure.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Apache ZooKeeper
documentation:
  - name: Apache ZooKeeper integration documentation
    description: |
      Unlock the power of ZooKeeper monitoring with the seamless integration of New Relic infrastructure.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/zookeeper-monitoring-integration/
keywords:
  - apache-zooKeeper
  - ZooKeeper
  - apache zookeeper
dataSourceIds:
  - apache-zookeeper
dashboards:
  - apache-zooKeeper
alertPolicies:
  - apache-zooKeeper
