id: shopify-hydrogen
displayName: Shopify Hydrogen Logs
description: |
  This integration will configure Shopify Hydrogen to send Logs to New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://shopify.dev/docs/custom-storefronts/hydrogen/logging#connecting-a-log-drain
keywords:
  - traffic
  - logs
  - agent
  - web app
  - shop
  - commerce
  - newrelic partner
categoryTerms:
  - newrelic partner
