slug: scikit-learn
description: |
  ## Why monitor your scikit-learn app?
  scikit-learn is a free software machine learning library for the Python programming language. scikit-learn monitoring ensures smooth operation and precise data insights.
  With this quickstart, you will:
  - Monitoring helps identify and address performance bottlenecks in scikit-learn applications, ensuring they operate efficiently and deliver a smooth user experience.
  - It enables the early detection of issues, such as slow response times or system errors, allowing for proactive troubleshooting and minimizing downtime.
  - Monitoring helps maintain a high level of user satisfaction by ensuring that scikit-learn platforms are responsive, reliable, and available when needed.
  
  ## Comprehensive monitoring quickstart for scikit-learn
  scikit-learn quickstart effectively monitors your scikit-learn application, gains insights into its performance and user engagement, and ensures it operates smoothly, securely, and efficiently in the education and research domains.

  ## What’s included in the scikit-learn quickstart?
  New Relic scikit-learn monitoring quickstart provides quality out-of-the-box reporting:
  - Gain real-time insights into your scikit-learn application's performance
  - Gain security insights for your scikit-learn application and detect potential threats
  - Gain code-related insights about your app's health and status

summary: |
    Use the New Relic scikit-learn quickstart to improve the performance of your scikit-learn application.
icon: logo.png
level: 
  - New Relic
  - Jyothi Surampudi
authors:
  - New Relic
title: scikit-learn
documentation:
  - name: scikit-learn integration documentation
    description: |
     Implement monitoring and instrumentation for your scikit-learn application, and ensure that your application's data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  scikit-learn
  -  scikit-learn ai
  -  scitkit learn
  -  scikit
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence