id: boomi
displayName: Boomi
description: |
  Send traces from Boomi to New Relic using OpenTelemetry.
icon: logo.png
install:
  primary:
    link:
      url: https://help.boomi.com/docs/atomsphere/flow/topics/flo-observability_collector_8b3010e3-51b1-43b5-8b09-9575e59610b0/#setting-up-the-apm-system-new-relic

keywords:
  - boomi
  - newrelic partner
categoryTerms:
  - newrelic partner
  - apm
