# A unique identifier for the data source
id: slack-notifications

# Display name for the data source
displayName: Slack Notifications

description: |
  Integrate New Relic with Slack to send notification messages to your Slack channels.

install:
  primary:
    link: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#slack

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - slack
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations
