slug: gridgain
title: GridGain

# Long-form description of the quickstart (required)
description: |
  # What is GridGain?
  GridGain is a unified real-time data platform that is designed to tackle speed and scale
  challenges. It is built on Apache Ignite, a top 5 ASF project.
  
  ## Getting started
  GridGain exports extensive metrics and this quickstart allows you to view them in New Relic.
  The same steps should also work with Apache Ignite. To get started with GridGain, please
  check out [the documentation](https://www.gridgain.com/docs/latest/).

  ## Dashboard
  This quickstart includes a sample dashboard. Note that the widgets included are reasonable
  default but will likely need to be updated depending on your configuration (persistence),
  use case (compute, caching) and product (snapshots, data center replication).
  
  ## More information
  More information can be found in [our documentation](https://docs.gridgain.com). Download
  GridGain [here](https://www.gridgain.com/download) or launch your own cluster in the
  cloud [here](https://portal.gridgain.com).
  
summary: |
  A quickstart for monitoring GridGain and Apache Ignite clusters.
  
level: Community

authors:
  - Stephen Darlington

keywords:
  - database
  - java
  - cluster
  - sql
  - cache
  - compute-grid
  - apache-ignite
  - ignite

# Reference to dashboards to be included in this quickstart
dashboards:
  - gridgain

# Documentation references
documentation:
  - name: Installation docs
    url: https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent
    description: Description about this doc reference

# Content / Design
icon: GridGain-Logo.jpg
website: https://www.gridgain.com
