id: redis-otel
displayName: Redis (OpenTelemetry)
description: |
  The OpenTelemetry Redis receiver enables the collection of metrics related to clients, connections, memory usage, network, and more.
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/other-examples/collector/redis

icon: logo.svg

keywords:
  - infrastructure
  - database
  - open telemetry
  - redis

categoryTerms:
  - infrastructure
