id: 475dec69-10c9-4bc6-8312-3caa266fb028

# Name of the quickstart
name: php

# Title of the quickstart
title: PHP

# Description of the quickstart
description: |+
  This is a quickstart for PHP applications.
  This quickstart relies on the New Relic PHP agent, with distributed tracing enabled (https://docs.newrelic.com/docs/agents/php-agent/features/distributed-tracing-php-agent/)

# Support level: New Relic | Verified | Community
level: New Relic

# Design
logo: logo.jpg
website: https://www.php.net/

# Authors of the quickstart
authors:
  - New Relic
  - Stijn Polfliet

documentation:
  - name: PHP
    description: >-
      PHP is a general-purpose scripting language especially suited to web development.
    url: https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your quickstart
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-apm
    name: php
keywords:
  - apm
  - php
  - language agent

installPlans:
  - php-agent
