slug: amazon-bedrock
description: |
  ## Why should you monitor Amazon Bedrock?
  Monitoring your Amazon Bedrock AI is essential for several reasons:
  ### Data drift detection: 
  Monitoring helps you detect and address data drift, ensuring that your models remain accurate and relevant as the data distribution evolves.
  ### Proactive issue detection:
  Monitoring helps you detect issues and anomalies in real-time.
  ### Performance optimization:
  Effective monitoring allows you to continuously assess the performance of your Amazon Bedrock AI models.

  ## Comprehensive monitoring quickstart for Amazon Bedrock
  Our Amazon Bedrock quickstart provides essential metrics like uptime, model accuracy, interference latency, and speed to optimize Amazon Bedrock's performance.

  ## What’s included in the Amazon Bedrock quickstart?
  New Relic Amazon Bedrock monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your Amazon Bedrock. These reports include:
  - Dashboards (average tokens, LLM completion’s details, chain’s details, tool details, top tool names and many more)
  - Alerts (errors, request per model and response time)
summary: |
  Use New Relic quickstart to monitor and analyze your Amazon Bedrock.
icon: logo.png
level:
  - New Relic
authors:
  - New Relic
  - Jyothi Surampudi
title: Amazon Bedrock
documentation:
  - name: Amazon Bedrock integration documentation
    description: |
      Implement monitoring and instrumentation for your Amazon Bedrock, and ensure that your Amazon Bedrock data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain
keywords:
  - amazon bedrock
  - amazon bedrock ai
  - amazonbedrock
  - bedrock
  - mlops
  - large language model
  - natural language processing
  - machine learning
  - artificial intelligence
  - ai
  - generative ai
alertPolicies:
  - langchain
dashboards:
  - langchain
