id: gigamon-appinsights
displayName: Gigamon Application Insights
description: |
  Gigamon Application Intelligence unlocks full visibility into applications running in datacenters and public clouds, and get to the root causes of vulnerabilities and performance bottlenecks.
icon: logo.png
install:
  primary:
    link:
      url: https://www.gigamon.com/partners/technology-partners.html#new-relic
keywords:
  - Gigamon
  - Gigamon Application Intelligence
  - Gigamon Integration
  - featured
  - security
  - packet capture
  - network
