id: port-monitoring
displayName: Port monitoring
description: |
  Efficient port monitoring is essential to understand context for status changes and respond quickly. Download the New Relic port monitoring quickstart to track your network port’s critical metrics and improve performance.
install:   
  primary:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: port-monitoring
    requires_account: false
icon: logo.svg
