# A unique identifier for the data source
id: gh-gates

# Display name for the data source
displayName: GitHub Deployment Protection Rules

description: |
  Deployment Protection Rules for GitHub Actions provides additional control to your CI/CD workflows.

install:
  primary:
    link:
      url: https://docs.newrelic.com/whats-new/2023/04/whats-new-04-20-github-integration/

# An icon for display within the catalog
icon: logo.svg

# Searchable words or phrases
keywords:
  - github
  - gates
  - anomaly detection
  - notifications
  - AIOps
  - Incident Intelligence
