id: langchain
displayName: LangChain
description: |
  Implement monitoring and instrumentation for your LangChain, and ensure that your LangChain data is integrated into New Relic for effective performance analysis and insights.
install:
  primary:
    link:
      url: https://github.com/newrelic/nr-openai-observability
icon: logo.png
keywords:
  -  langchain
  -  langchain ai
  -  lang
  -  chain
  -  ai
  -  lang chain
  -  large language model
  -  natural language processing
  -  machine learning
  -  artificial intelligence