id: hcp-consul-otel
displayName: HCP Consul (OTeL)
description: |
  This guide details how to set up an OTeL collector to monitor your Hashicorp HCP Consul environment with New Relic.

icon: logo.svg
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hcp-consul/
  fallback:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/infrastructure-integrations/cloud-integrations/hcp-consul-monitoring
keywords:
  - hashicorp
  - hcp
  - cloud
  - infrastructure
  - newrelic partner
  - opentelemetry
categoryTerms:
  - newrelic partner
  - infrastructure
