id: singlestore
displayName: SingleStore OpenTelemetry
description: |
  This integration runs an OpenTelemetry collector to collect and send metrics to New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/other-examples/collector/singlestore
keywords:
  - metrics
  - database
  - singlestore
  - opentelemetry
  - newrelic partner
categoryTerms:
  - newrelic partner
