id: singlestore
displayName: SingleStore OpenTelemetry
description: |
  This integration runs an OpenTelemetry collector to collect and send metrics to New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-singlestore/
keywords:
  - metrics
  - database
  - singlestore
  - opentelemetry
  - newrelic partner
categoryTerms:
  - newrelic partner
