id: activemq
displayName: ActiveMQ
description: |
  New Relic detects your Apache ActiveMQ metrics like queues, brokers, producers, consumers, garbage collection rate, heap memory usage and more.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: activemq
      requiresAccount: false
icon: logo.png