id: hivemq-integration-docs
displayName: HiveMQ integration
description: |
  The New Relic HiveMQ integration allows you to monitor your HiveMQ objects like messages, caches and more.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-hivemq/

icon: logo.svg
