# Name of the quickstart
slug: langchain-vectordb

# Title of the quickstart
title: LangChain Vector Database

summary: |
  A vector store takes care of storing embedded data and performing vector search on the vector database
# Description of the quickstart
description: |
  ## Why monitor LangChain Vector Database?
  LangChain is a framework for developing applications powered by language models. 
  By monitoring your LangChain app, we are providing you visibility on the chains, tools as well as inputs and outputs. 
  Monitoring can help optimize the performance of systems or applications that rely on vector data. For databases associated with hardware or equipment, monitoring can enable predictive maintenance by tracking usage and performance metrics to anticipate and prevent failures
 
  ## Comprehensive monitoring quickstart for LangChain
  Our LangChain Vector Database quickstart provides metrics, including response time, zero documents retreived and many more. These metrics serve as valuable tools to empower you in maximizing the performance of LangChain Vector Database.
 
  ## What’s included in this quickstart?
    New Relic LangChain Vector Database monitoring quickstart provides a variety of pre-built reports, which will help you gain insights into the health and performance of your LangChain. These reports include:
  - Code-related insights to identify potential problems with your code and improve its performance
  - Latency details and number of tokens
  - Entity details such as the average number of tokens used, the cost per entity, and the total number of requests made
  - Alerts for errors,requests per model and response time

# The logo of the quickstart
icon: logo.png

# Support level
level: New Relic

# Authors of the quickstart
authors:
  - New Relic

keywords:
  - langchain vector database
  - langchain ai
  - vector database
  - ai
  - lang chain
  - large language model
  - natural language processing
  - machine learning
  - artificial intelligence
  - mlops
  - NR1_addData

dashboards:
  - langchain-vectordb
alertPolicies:
  - langchain-vectordb

documentation:
  - name: LangChain Vector Database integration documentation
    description: |
     Implement monitoring and instrumentation for your LangChain Vector Database, and ensure that your LangChain Vector Database data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic/nr-openai-observability

dataSourceIds:
  - langchain-vectordb
