id: newrelic-java-vertx
displayName: New Relic Java Instrumentation for Vert.x Event Bus
description: |
  Provides instrumentation code for monitoring the Vert.x Event Bus. Tracks flow across the event bus.
  Vertx-Verticles provides instrumentation for classes extends AbstractVerticle. It does this by 
  instrumenting each class that is deployed. 
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/java-integrations/vertx-eventbus-integration/
icon: vertx.svg
keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - eventbus
  - NR1_addData