id: apache-hadoop
displayName: Apache Hadoop
description: |
  Optimize your Apache Hadoop performance using New Relic Apache Hadoop monitoring.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/
keywords:
  - apache-hadoop
  - apache