slug: singlestore
description: |
  ## About this integration
    This integration uses an OpenTelemetry(OTeL) collector to gather metrics from [SingleStore's management API](https://docs.singlestore.com/cloud/reference/management-api/reference/) and visualize them in New Relic.

  ## What does this integration cover?
    This integration gives you complete visibility into your resource utilization and workload statistics for your Singlestore Database.

summary: |
  Monitor the performance of your SingleStore database using OTeL.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Joseph Counts
title: SingleStore OpenTelemetry(OTeL)
documentation:
  - name: SingleStore OpenTelemetry setup documentation
    description: |
      Set up an OTeL collector to monitor your SingleStoreDB instance.
    url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-singlestore/
dataSourceIds:
  - singlestore
keywords:
  - singlestoredb
  - opentelemetry
  - database
  - cloud db
  - newrelic partner
  - NR1_addData
  - NR1_sys
dashboards:
  - singlestore
