slug: amazon-timestream
description: |-
  ## What is Amazon Timestream?
  Amazon Timestream is a fast, scalable, and serverless time-series database service that makes it easier to store and analyze trillions of events per day up to 1,000 times faster. Amazon Timestream automatically scales up or down to adjust capacity and performance, so that you don’t have to manage the underlying infrastructure.
  ### Get started!
  Start monitoring Amazon Timestream by connecting Amazon Web Services (AWS) to New Relic! Take a look at our documentation for information on how to set this integration.
  ### More info
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-timestream-monitoring-integration/) to learn more about New Relic monitoring for Amazon Timestream.
summary: |-
  Monitor Amazon Timestream by connecting AWS to New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Amazon Timestream
documentation:
  - name: Amazon Timestream installation docs
    description: |
      Monitor Amazon Timestream by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-timestream-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - timestream
dashboards:
  - amazon-timestream
dataSourceIds:
  - amazon-cloudwatch-metric-streams
alertPolicies:
  - amazon-timestream