id: traceloop
displayName: Traceloop
description: |
  Monitor and analyze your Traceloop LLM observability with New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/opentelemetry/get-started/traceloop-llm-observability/traceloop-llm-observability-intro/
keywords:
  - traceloop
  - traceloop llm observability
  - llm observability