# A unique identifier for the data source
id: servicenow-notifications

# Display name for the data source
displayName: ServiceNow Notifications

description: |
  With our ServiceNow integration, sync issues caught in New Relic with ServiceNow incidents. Check out our documentation to set up ServiceNow destinations and configure a message template, so your personnel are always informed.

install:
  primary:
    link: https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#servicenow

# An icon for display within the catalog
icon: logo.png

# Searchable words or phrases
keywords:
  - servicenow
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations
