id: 87bd9d20-a193-4aa8-80f7-a1f5c65278f1
slug: vmware-vsphere
description: Enterprise Workload Platform for Traditional and Next Gen Apps
summary: Enterprise Workload Platform for Traditional and Next Gen Apps
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: VMware vSphere
documentation:
  - name: VMware vSphere installation docs
    description: |
      Enterprise Workload Platform for Traditional and Next Gen Apps
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/
keywords:
  - infrastructure
installPlans:
  - vsphere-integration
dataSourceIds:
  - vmware-vsphere
