id: okhttp
displayName: OKHTTP
description: OkHttp is a third-party library developed by Square for sending and receive HTTP-based network requests.
install:   
  primary:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: okhttp
    requires_account: false
icon: logo.png
