id: okhttp
displayName: OKHTTP
description: OkHttp is a third-party library developed by Square for sending and receive HTTP-based network requests.
install:
  flagged:
    type: nerdlet
    nerdlet_id: marketplace.install-data-source
    nerdlet_state:
      dataSourceId: okhttp
    requires_account: false
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-proguard-or-dexguard-android-apps
icon: logo.png
