id: f53aad6e-dbdd-4ed3-a9a3-90a8d81187f6
slug: nvidia-triton
description: |
  ## Why monitor NVIDIA Triton?
  Monitoring ensures optimal performance of your Triton server by tracking metrics such as GPU utilization, memory usage, and inference latency. This allows you to identify bottlenecks and refine your server configuration to enhance performance.
  
  ## Comprehensive monitoring quickstart for NVIDIA Triton
  Monitoring provides a thorough evaluation of NVIDIA GPU health, encompassing memory usage, temperature, HTTP request errors, CPU utilization, and power consumption. 

  ## What’s included in this quickstart?
  New Relic NVIDIA Triton monitoring quickstart ability to cover quality on out-of-the-box reporting.
  - Dashboards (HTTP requests, CPU utilization, Pinned pool memory total and used)
  - Alerts (CPU used percentage, Storage used percentage and etc)

summary: |
   Monitor and analyze your NVIDIA Triton inference server with New Relic.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Praveen Kudikyala
title: NVIDIA Triton
documentation:
  - name: NVIDIA Triton integration documentation
    description: |
      Monitor and instrument your NVIDIA Triton with New Relic to gain deep insights into your performance.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nvidia-triton-integration/
keywords:
  - NVIDIA Triton inference server
  - AI Acceleration
  - Machine Learning Acceleration
  - GPU Management
  - AI Management
  - Machine Learning Management
  - Deep Learning Performance
  - AI Performance
  - GPU Optimization
  - AI Optimization
  - inference server
  - NR1_addData
  - NR1_sys
dataSourceIds:
  - nvidia-triton
dashboards:
  - nvidia-triton
alertPolicies:
  - nvidia-triton