name: Move content PR to Project Board

on:
  pull_request_target:
    types: [opened]
    paths:
      - "quickstarts/**"

env:
  GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}

jobs:
  move-pr-to-project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Move PR to Project Board for triage
        run: |
          gh pr edit ${{github.event.pull_request.number}} --add-project "NR1 Quickstarts Community"
