name: Tests

on:
  push:
    paths:
      - "utils/**"
  pull_request:
    paths:
      - "utils/**"

jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup workspace
        uses: "./.github/actions/bootstrap"

      - name: Run tests
        run: cd utils && yarn test
