name: Validate PR Artifact

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.sha }}
      - name: Setup workspace
        uses: "./.github/actions/bootstrap"
      - name: Validate PR Artifact
        uses: "./.github/actions/build-validate-artifact"
        with:
          command-args: '--output-artifact'
          #command-args: ${{ github.ref == 'refs/heads/main' && '--output-artifact' || '' }}
      - name: Debugging output
        run: ls -la utils/build
      - name: Upload artifact
      #if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          path: utils/build
          #   release:
          #     needs: validate
          #     steps: 
