name: Lint Yaml

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  lint-yaml-files:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@${{ vars.ACTIONS_CHECKOUT_SHA }}

      - name: Run yamllint
        run: |
          yamllint -f parsable -c ./.config/yamllint/config.yml .
