id: amazon-timestream
displayName: Amazon Timestream
description: Monitor Amazon Timestream by sending Access logs to New Relic
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-timestream-monitoring-integration/
icon: logo.png